# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # API utility class
  class APIHelper < CoreLibrary::ApiHelper
  end
end
