# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  #  slack_web_api client class.
  class Client
    include CoreLibrary
    attr_reader :config, :auth_managers

    def user_agent_detail
      config.user_agent_detail
    end

    # Returns the configured authentication slackAuth instance.
    def slack_auth
      @auth_managers['slackAuth']
    end

    # Access to admin_apps controller.
    # @return [AdminAppsApi] Returns the controller instance.
    def admin_apps
      @admin_apps ||= AdminAppsApi.new @global_configuration
    end

    # Access to admin_apps_approved controller.
    # @return [AdminAppsApprovedApi] Returns the controller instance.
    def admin_apps_approved
      @admin_apps_approved ||= AdminAppsApprovedApi.new @global_configuration
    end

    # Access to admin_apps_requests controller.
    # @return [AdminAppsRequestsApi] Returns the controller instance.
    def admin_apps_requests
      @admin_apps_requests ||= AdminAppsRequestsApi.new @global_configuration
    end

    # Access to admin_apps_restricted controller.
    # @return [AdminAppsRestrictedApi] Returns the controller instance.
    def admin_apps_restricted
      @admin_apps_restricted ||= AdminAppsRestrictedApi.new @global_configuration
    end

    # Access to admin_conversations controller.
    # @return [AdminConversationsApi] Returns the controller instance.
    def admin_conversations
      @admin_conversations ||= AdminConversationsApi.new @global_configuration
    end

    # Access to admin_conversations_ekm controller.
    # @return [AdminConversationsEkmApi] Returns the controller instance.
    def admin_conversations_ekm
      @admin_conversations_ekm ||= AdminConversationsEkmApi.new @global_configuration
    end

    # Access to admin_conversations_restrict_access controller.
    # @return [AdminConversationsRestrictAccessApi] Returns the controller instance.
    def admin_conversations_restrict_access
      @admin_conversations_restrict_access ||= AdminConversationsRestrictAccessApi.new @global_configuration
    end

    # Access to admin_emoji controller.
    # @return [AdminEmojiApi] Returns the controller instance.
    def admin_emoji
      @admin_emoji ||= AdminEmojiApi.new @global_configuration
    end

    # Access to admin_invite_requests controller.
    # @return [AdminInviteRequestsApi] Returns the controller instance.
    def admin_invite_requests
      @admin_invite_requests ||= AdminInviteRequestsApi.new @global_configuration
    end

    # Access to admin_invite_requests_approved controller.
    # @return [AdminInviteRequestsApprovedApi] Returns the controller instance.
    def admin_invite_requests_approved
      @admin_invite_requests_approved ||= AdminInviteRequestsApprovedApi.new @global_configuration
    end

    # Access to admin_invite_requests_denied controller.
    # @return [AdminInviteRequestsDeniedApi] Returns the controller instance.
    def admin_invite_requests_denied
      @admin_invite_requests_denied ||= AdminInviteRequestsDeniedApi.new @global_configuration
    end

    # Access to admin_teams_admins controller.
    # @return [AdminTeamsAdminsApi] Returns the controller instance.
    def admin_teams_admins
      @admin_teams_admins ||= AdminTeamsAdminsApi.new @global_configuration
    end

    # Access to admin_teams controller.
    # @return [AdminTeamsApi] Returns the controller instance.
    def admin_teams
      @admin_teams ||= AdminTeamsApi.new @global_configuration
    end

    # Access to admin_teams_owners controller.
    # @return [AdminTeamsOwnersApi] Returns the controller instance.
    def admin_teams_owners
      @admin_teams_owners ||= AdminTeamsOwnersApi.new @global_configuration
    end

    # Access to admin_teams_settings controller.
    # @return [AdminTeamsSettingsApi] Returns the controller instance.
    def admin_teams_settings
      @admin_teams_settings ||= AdminTeamsSettingsApi.new @global_configuration
    end

    # Access to admin_usergroups controller.
    # @return [AdminUsergroupsApi] Returns the controller instance.
    def admin_usergroups
      @admin_usergroups ||= AdminUsergroupsApi.new @global_configuration
    end

    # Access to admin_users controller.
    # @return [AdminUsersApi] Returns the controller instance.
    def admin_users
      @admin_users ||= AdminUsersApi.new @global_configuration
    end

    # Access to admin_users_session controller.
    # @return [AdminUsersSessionApi] Returns the controller instance.
    def admin_users_session
      @admin_users_session ||= AdminUsersSessionApi.new @global_configuration
    end

    # Access to api controller.
    # @return [Api] Returns the controller instance.
    def api
      @api ||= Api.new @global_configuration
    end

    # Access to apps_event_authorizations controller.
    # @return [AppsEventAuthorizationsApi] Returns the controller instance.
    def apps_event_authorizations
      @apps_event_authorizations ||= AppsEventAuthorizationsApi.new @global_configuration
    end

    # Access to apps_permissions controller.
    # @return [AppsPermissionsApi] Returns the controller instance.
    def apps_permissions
      @apps_permissions ||= AppsPermissionsApi.new @global_configuration
    end

    # Access to apps_permissions_resources controller.
    # @return [AppsPermissionsResourcesApi] Returns the controller instance.
    def apps_permissions_resources
      @apps_permissions_resources ||= AppsPermissionsResourcesApi.new @global_configuration
    end

    # Access to apps_permissions_scopes controller.
    # @return [AppsPermissionsScopesApi] Returns the controller instance.
    def apps_permissions_scopes
      @apps_permissions_scopes ||= AppsPermissionsScopesApi.new @global_configuration
    end

    # Access to apps_permissions_users controller.
    # @return [AppsPermissionsUsersApi] Returns the controller instance.
    def apps_permissions_users
      @apps_permissions_users ||= AppsPermissionsUsersApi.new @global_configuration
    end

    # Access to apps controller.
    # @return [AppsApi] Returns the controller instance.
    def apps
      @apps ||= AppsApi.new @global_configuration
    end

    # Access to auth controller.
    # @return [AuthApi] Returns the controller instance.
    def auth
      @auth ||= AuthApi.new @global_configuration
    end

    # Access to bots controller.
    # @return [BotsApi] Returns the controller instance.
    def bots
      @bots ||= BotsApi.new @global_configuration
    end

    # Access to calls controller.
    # @return [CallsApi] Returns the controller instance.
    def calls
      @calls ||= CallsApi.new @global_configuration
    end

    # Access to calls_participants controller.
    # @return [CallsParticipantsApi] Returns the controller instance.
    def calls_participants
      @calls_participants ||= CallsParticipantsApi.new @global_configuration
    end

    # Access to chat controller.
    # @return [ChatApi] Returns the controller instance.
    def chat
      @chat ||= ChatApi.new @global_configuration
    end

    # Access to chat_scheduled_messages controller.
    # @return [ChatScheduledMessagesApi] Returns the controller instance.
    def chat_scheduled_messages
      @chat_scheduled_messages ||= ChatScheduledMessagesApi.new @global_configuration
    end

    # Access to conversations controller.
    # @return [ConversationsApi] Returns the controller instance.
    def conversations
      @conversations ||= ConversationsApi.new @global_configuration
    end

    # Access to dialog controller.
    # @return [DialogApi] Returns the controller instance.
    def dialog
      @dialog ||= DialogApi.new @global_configuration
    end

    # Access to dnd controller.
    # @return [DndApi] Returns the controller instance.
    def dnd
      @dnd ||= DndApi.new @global_configuration
    end

    # Access to emoji controller.
    # @return [EmojiApi] Returns the controller instance.
    def emoji
      @emoji ||= EmojiApi.new @global_configuration
    end

    # Access to files_comments controller.
    # @return [FilesCommentsApi] Returns the controller instance.
    def files_comments
      @files_comments ||= FilesCommentsApi.new @global_configuration
    end

    # Access to files controller.
    # @return [FilesApi] Returns the controller instance.
    def files
      @files ||= FilesApi.new @global_configuration
    end

    # Access to files_remote controller.
    # @return [FilesRemoteApi] Returns the controller instance.
    def files_remote
      @files_remote ||= FilesRemoteApi.new @global_configuration
    end

    # Access to migration controller.
    # @return [MigrationApi] Returns the controller instance.
    def migration
      @migration ||= MigrationApi.new @global_configuration
    end

    # Access to oauth controller.
    # @return [OauthApi] Returns the controller instance.
    def oauth
      @oauth ||= OauthApi.new @global_configuration
    end

    # Access to oauth_v2 controller.
    # @return [OauthV2Api] Returns the controller instance.
    def oauth_v2
      @oauth_v2 ||= OauthV2Api.new @global_configuration
    end

    # Access to pins controller.
    # @return [PinsApi] Returns the controller instance.
    def pins
      @pins ||= PinsApi.new @global_configuration
    end

    # Access to reactions controller.
    # @return [ReactionsApi] Returns the controller instance.
    def reactions
      @reactions ||= ReactionsApi.new @global_configuration
    end

    # Access to reminders controller.
    # @return [RemindersApi] Returns the controller instance.
    def reminders
      @reminders ||= RemindersApi.new @global_configuration
    end

    # Access to rtm controller.
    # @return [RtmApi] Returns the controller instance.
    def rtm
      @rtm ||= RtmApi.new @global_configuration
    end

    # Access to search controller.
    # @return [SearchApi] Returns the controller instance.
    def search
      @search ||= SearchApi.new @global_configuration
    end

    # Access to stars controller.
    # @return [StarsApi] Returns the controller instance.
    def stars
      @stars ||= StarsApi.new @global_configuration
    end

    # Access to team controller.
    # @return [TeamApi] Returns the controller instance.
    def team
      @team ||= TeamApi.new @global_configuration
    end

    # Access to team_profile controller.
    # @return [TeamProfileApi] Returns the controller instance.
    def team_profile
      @team_profile ||= TeamProfileApi.new @global_configuration
    end

    # Access to usergroups controller.
    # @return [UsergroupsApi] Returns the controller instance.
    def usergroups
      @usergroups ||= UsergroupsApi.new @global_configuration
    end

    # Access to usergroups_users controller.
    # @return [UsergroupsUsersApi] Returns the controller instance.
    def usergroups_users
      @usergroups_users ||= UsergroupsUsersApi.new @global_configuration
    end

    # Access to users controller.
    # @return [UsersApi] Returns the controller instance.
    def users
      @users ||= UsersApi.new @global_configuration
    end

    # Access to users_profile controller.
    # @return [UsersProfileApi] Returns the controller instance.
    def users_profile
      @users_profile ||= UsersProfileApi.new @global_configuration
    end

    # Access to views controller.
    # @return [ViewsApi] Returns the controller instance.
    def views
      @views ||= ViewsApi.new @global_configuration
    end

    # Access to workflows controller.
    # @return [WorkflowsApi] Returns the controller instance.
    def workflows
      @workflows ||= WorkflowsApi.new @global_configuration
    end

    # Access to o_auth_authorization controller.
    # @return [OAuthAuthorizationApi] Returns the controller instance.
    def o_auth_authorization
      @o_auth_authorization ||= OAuthAuthorizationApi.new @global_configuration
    end

    def initialize(
      connection: nil, adapter: :net_http_persistent, timeout: 30,
      max_retries: 0, retry_interval: 1, backoff_factor: 2,
      retry_statuses: [408, 413, 429, 500, 502, 503, 504, 521, 522, 524],
      retry_methods: %i[get put], http_callback: nil, proxy_settings: nil,
      logging_configuration: nil, environment: Environment::PRODUCTION,
      authorization_code_auth_credentials: nil, config: nil
    )
      @config = if config.nil?
                  Configuration.new(
                    connection: connection, adapter: adapter, timeout: timeout,
                    max_retries: max_retries, retry_interval: retry_interval,
                    backoff_factor: backoff_factor,
                    retry_statuses: retry_statuses,
                    retry_methods: retry_methods, http_callback: http_callback,
                    proxy_settings: proxy_settings,
                    logging_configuration: logging_configuration,
                    environment: environment,
                    authorization_code_auth_credentials: authorization_code_auth_credentials
                  )
                else
                  config
                end
      user_agent_params = BaseApi.user_agent_parameters

      @global_configuration = GlobalConfiguration.new(client_configuration: @config)
                                                 .base_uri_executor(@config.method(:get_base_uri))
                                                 .global_errors(BaseApi::GLOBAL_ERRORS)
                                                 .user_agent(BaseApi.user_agent,
                                                             agent_parameters: user_agent_params)

      initialize_auth_managers(@global_configuration)
      @global_configuration = @global_configuration.auth_managers(@auth_managers)
    end

    # Initializes the auth managers hash used for authenticating API calls.
    # @param [GlobalConfiguration] global_config The global configuration of the SDK)
    def initialize_auth_managers(global_config)
      @auth_managers = {}
      http_client_config = global_config.client_configuration
      %w[slackAuth].each { |auth| @auth_managers[auth] = nil }
      @auth_managers['slackAuth'] = OAuth2.new(
        http_client_config.authorization_code_auth_credentials, global_config
      )
    end

    # Creates a client directly from environment variables.
    def self.from_env(**overrides)
      default_config = Configuration.build_default_config_from_env
      new_config = default_config.clone_with(**overrides)
      new(config: new_config)
    end
  end
end
