# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # AdminConversationsRestrictAccessApi
  class AdminConversationsRestrictAccessApi < BaseApi
    # Add an allowlist of IDP groups for accessing a channel
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `admin.conversations:write`
    # @param [String] group_id Required parameter: The [IDP
    # Group](https://slack.com/help/articles/115001435788-Connect-identity-provi
    # der-groups-to-your-Enterprise-Grid-org) ID to be an allowlist for the
    # private channel.
    # @param [String] channel_id Required parameter: The channel to link this
    # group to.
    # @param [String] team_id Optional parameter: The workspace where the
    # channel exists. This argument is required for channels only tied to one
    # workspace, and optional for channels that are shared across an
    # organization.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def admin_conversations_restrict_access_add_group(token,
                                                      group_id,
                                                      channel_id,
                                                      team_id: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/admin.conversations.restrictAccess.addGroup',
                                     Server::DEFAULT)
                   .form_param(new_parameter(token, key: 'token')
                                .is_required(true))
                   .form_param(new_parameter(group_id, key: 'group_id')
                                .is_required(true))
                   .form_param(new_parameter(channel_id, key: 'channel_id')
                                .is_required(true))
                   .form_param(new_parameter(team_id, key: 'team_id'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(DefaultSuccessTemplate.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 DefaultErrorTemplateException))
        .execute
    end

    # List all IDP Groups linked to a channel
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `admin.conversations:read`
    # @param [String] channel_id Required parameter: TODO: type description
    # here
    # @param [String] team_id Optional parameter: The workspace where the
    # channel exists. This argument is required for channels only tied to one
    # workspace, and optional for channels that are shared across an
    # organization.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def admin_conversations_restrict_access_list_groups(token,
                                                        channel_id,
                                                        team_id: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/admin.conversations.restrictAccess.listGroups',
                                     Server::DEFAULT)
                   .query_param(new_parameter(token, key: 'token')
                                 .is_required(true))
                   .query_param(new_parameter(channel_id, key: 'channel_id')
                                 .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .query_param(new_parameter(team_id, key: 'team_id'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(DefaultSuccessTemplate.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 DefaultErrorTemplateException))
        .execute
    end

    # Remove a linked IDP group linked from a private channel
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `admin.conversations:write`
    # @param [String] team_id Required parameter: The workspace where the
    # channel exists. This argument is required for channels only tied to one
    # workspace, and optional for channels that are shared across an
    # organization.
    # @param [String] group_id Required parameter: The [IDP
    # Group](https://slack.com/help/articles/115001435788-Connect-identity-provi
    # der-groups-to-your-Enterprise-Grid-org) ID to remove from the private
    # channel.
    # @param [String] channel_id Required parameter: The channel to remove the
    # linked group from.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def admin_conversations_restrict_access_remove_group(token,
                                                         team_id,
                                                         group_id,
                                                         channel_id)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/admin.conversations.restrictAccess.removeGroup',
                                     Server::DEFAULT)
                   .form_param(new_parameter(token, key: 'token')
                                .is_required(true))
                   .form_param(new_parameter(team_id, key: 'team_id')
                                .is_required(true))
                   .form_param(new_parameter(group_id, key: 'group_id')
                                .is_required(true))
                   .form_param(new_parameter(channel_id, key: 'channel_id')
                                .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(DefaultSuccessTemplate.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 DefaultErrorTemplateException))
        .execute
    end
  end
end
