# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # AdminInviteRequestsDeniedApi
  class AdminInviteRequestsDeniedApi < BaseApi
    # List all denied workspace invite requests.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `admin.invites:read`
    # @param [String] team_id Optional parameter: ID for the workspace where the
    # invite requests were made.
    # @param [String] cursor Optional parameter: Value of the `next_cursor`
    # field sent as part of the previous api response
    # @param [Integer] limit Optional parameter: The number of results that will
    # be returned by the API on each invocation. Must be between 1 - 1000 both
    # inclusive
    # @return [ApiResponse] Complete http response with raw body and status code.
    def admin_invite_requests_denied_list(token,
                                          team_id: nil,
                                          cursor: nil,
                                          limit: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/admin.inviteRequests.denied.list',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .query_param(new_parameter(team_id, key: 'team_id'))
                   .query_param(new_parameter(cursor, key: 'cursor'))
                   .query_param(new_parameter(limit, key: 'limit'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(DefaultSuccessTemplate.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 DefaultErrorTemplateException))
        .execute
    end
  end
end
