# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # AdminUsersSessionApi
  class AdminUsersSessionApi < BaseApi
    # Invalidate a single session for a user by session_id
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `admin.users:write`
    # @param [String] team_id Required parameter: ID of the team that the
    # session belongs to
    # @param [Integer] session_id Required parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def admin_users_session_invalidate(token,
                                       team_id,
                                       session_id)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/admin.users.session.invalidate',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .form_param(new_parameter(team_id, key: 'team_id')
                                .is_required(true))
                   .form_param(new_parameter(session_id, key: 'session_id')
                                .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(DefaultSuccessTemplate.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 DefaultErrorTemplateException))
        .execute
    end

    # Wipes all valid sessions on all devices for a given user
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `admin.users:write`
    # @param [String] user_id Required parameter: The ID of the user to wipe
    # sessions for
    # @param [TrueClass | FalseClass] mobile_only Optional parameter: Only
    # expire mobile sessions (default: false)
    # @param [TrueClass | FalseClass] web_only Optional parameter: Only expire
    # web sessions (default: false)
    # @return [ApiResponse] Complete http response with raw body and status code.
    def admin_users_session_reset(token,
                                  user_id,
                                  mobile_only: nil,
                                  web_only: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/admin.users.session.reset',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .form_param(new_parameter(user_id, key: 'user_id')
                                .is_required(true))
                   .form_param(new_parameter(mobile_only, key: 'mobile_only'))
                   .form_param(new_parameter(web_only, key: 'web_only'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(DefaultSuccessTemplate.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 DefaultErrorTemplateException))
        .execute
    end
  end
end
