# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # AdminUsergroupsApi
  class AdminUsergroupsApi < BaseApi
    # Add one or more default channels to an IDP group.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `admin.usergroups:write`
    # @param [String] usergroup_id Required parameter: ID of the IDP group to
    # add default channels for.
    # @param [String] channel_ids Required parameter: Comma separated string of
    # channel IDs.
    # @param [String] team_id Optional parameter: The workspace to add default
    # channels in.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def admin_usergroups_add_channels(token,
                                      usergroup_id,
                                      channel_ids,
                                      team_id: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/admin.usergroups.addChannels',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .form_param(new_parameter(usergroup_id, key: 'usergroup_id')
                                .is_required(true))
                   .form_param(new_parameter(channel_ids, key: 'channel_ids')
                                .is_required(true))
                   .form_param(new_parameter(team_id, key: 'team_id'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(DefaultSuccessTemplate.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response if the token provided is not associated'\
                                  ' with an Org Admin or Owner',
                                 DefaultErrorTemplateException))
        .execute
    end

    # Associate one or more default workspaces with an organization-wide IDP
    # group.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `admin.teams:write`
    # @param [String] usergroup_id Required parameter: An encoded usergroup (IDP
    # Group) ID.
    # @param [String] team_ids Required parameter: A comma separated list of
    # encoded team (workspace) IDs. Each workspace *MUST* belong to the
    # organization associated with the token.
    # @param [TrueClass | FalseClass] auto_provision Optional parameter: When
    # `true`, this method automatically creates new workspace accounts for the
    # IDP group members.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def admin_usergroups_add_teams(token,
                                   usergroup_id,
                                   team_ids,
                                   auto_provision: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/admin.usergroups.addTeams',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .form_param(new_parameter(usergroup_id, key: 'usergroup_id')
                                .is_required(true))
                   .form_param(new_parameter(team_ids, key: 'team_ids')
                                .is_required(true))
                   .form_param(new_parameter(auto_provision, key: 'auto_provision'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(DefaultSuccessTemplate.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 DefaultErrorTemplateException))
        .execute
    end

    # List the channels linked to an org-level IDP group (user group).
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `admin.usergroups:read`
    # @param [String] usergroup_id Required parameter: ID of the IDP group to
    # list default channels for.
    # @param [String] team_id Optional parameter: ID of the the workspace.
    # @param [TrueClass | FalseClass] include_num_members Optional parameter:
    # Flag to include or exclude the count of members per channel.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def admin_usergroups_list_channels(token,
                                       usergroup_id,
                                       team_id: nil,
                                       include_num_members: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/admin.usergroups.listChannels',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .query_param(new_parameter(usergroup_id, key: 'usergroup_id')
                                 .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .query_param(new_parameter(team_id, key: 'team_id'))
                   .query_param(new_parameter(include_num_members, key: 'include_num_members'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(DefaultSuccessTemplate.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response if the token provided is not associated'\
                                  ' with an Org Admin or Owner',
                                 DefaultErrorTemplateException))
        .execute
    end

    # Remove one or more default channels from an org-level IDP group (user
    # group).
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `admin.usergroups:write`
    # @param [String] usergroup_id Required parameter: ID of the IDP Group
    # @param [String] channel_ids Required parameter: Comma-separated string of
    # channel IDs
    # @return [ApiResponse] Complete http response with raw body and status code.
    def admin_usergroups_remove_channels(token,
                                         usergroup_id,
                                         channel_ids)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/admin.usergroups.removeChannels',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .form_param(new_parameter(usergroup_id, key: 'usergroup_id')
                                .is_required(true))
                   .form_param(new_parameter(channel_ids, key: 'channel_ids')
                                .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(DefaultSuccessTemplate.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response if the token provided is not associated'\
                                  ' with an Org Admin or Owner',
                                 DefaultErrorTemplateException))
        .execute
    end
  end
end
