# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # AdminAppsApi
  class AdminAppsApi < BaseApi
    # Approve an app for installation on a workspace.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `admin.apps:write`
    # @param [String] app_id Optional parameter: The id of the app to approve.
    # @param [String] request_id Optional parameter: The id of the request to
    # approve.
    # @param [String] team_id Optional parameter: TODO: type description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def admin_apps_approve(token,
                           app_id: nil,
                           request_id: nil,
                           team_id: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/admin.apps.approve',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .form_param(new_parameter(app_id, key: 'app_id'))
                   .form_param(new_parameter(request_id, key: 'request_id'))
                   .form_param(new_parameter(team_id, key: 'team_id'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(DefaultSuccessTemplate.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 DefaultErrorTemplateException))
        .execute
    end

    # Restrict an app for installation on a workspace.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `admin.apps:write`
    # @param [String] app_id Optional parameter: The id of the app to
    # restrict.
    # @param [String] request_id Optional parameter: The id of the request to
    # restrict.
    # @param [String] team_id Optional parameter: TODO: type description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def admin_apps_restrict(token,
                            app_id: nil,
                            request_id: nil,
                            team_id: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/admin.apps.restrict',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .form_param(new_parameter(app_id, key: 'app_id'))
                   .form_param(new_parameter(request_id, key: 'request_id'))
                   .form_param(new_parameter(team_id, key: 'team_id'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(DefaultSuccessTemplate.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 DefaultErrorTemplateException))
        .execute
    end
  end
end
