# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # AdminAppsRestrictedApi
  class AdminAppsRestrictedApi < BaseApi
    # List restricted apps for an org or workspace.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `admin.apps:read`
    # @param [Integer] limit Optional parameter: The maximum number of items to
    # return. Must be between 1 - 1000 both inclusive.
    # @param [String] cursor Optional parameter: Set `cursor` to `next_cursor`
    # returned by the previous call to list items in the next page
    # @param [String] team_id Optional parameter: TODO: type description here
    # @param [String] enterprise_id Optional parameter: TODO: type description
    # here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def admin_apps_restricted_list(token,
                                   limit: nil,
                                   cursor: nil,
                                   team_id: nil,
                                   enterprise_id: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/admin.apps.restricted.list',
                                     Server::DEFAULT)
                   .query_param(new_parameter(token, key: 'token')
                                 .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .query_param(new_parameter(limit, key: 'limit'))
                   .query_param(new_parameter(cursor, key: 'cursor'))
                   .query_param(new_parameter(team_id, key: 'team_id'))
                   .query_param(new_parameter(enterprise_id, key: 'enterprise_id'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(DefaultSuccessTemplate.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 DefaultErrorTemplateException))
        .execute
    end
  end
end
