# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # AdminUsersApi
  class AdminUsersApi < BaseApi
    # Add an Enterprise user to a workspace.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `admin.users:write`
    # @param [String] team_id Required parameter: The ID (`T1234`) of the
    # workspace.
    # @param [String] user_id Required parameter: The ID of the user to add to
    # the workspace.
    # @param [TrueClass | FalseClass] is_restricted Optional parameter: True if
    # user should be added to the workspace as a guest.
    # @param [TrueClass | FalseClass] is_ultra_restricted Optional parameter:
    # True if user should be added to the workspace as a single-channel guest.
    # @param [String] channel_ids Optional parameter: Comma separated values of
    # channel IDs to add user in the new workspace.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def admin_users_assign(token,
                           team_id,
                           user_id,
                           is_restricted: nil,
                           is_ultra_restricted: nil,
                           channel_ids: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/admin.users.assign',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .form_param(new_parameter(team_id, key: 'team_id')
                                .is_required(true))
                   .form_param(new_parameter(user_id, key: 'user_id')
                                .is_required(true))
                   .form_param(new_parameter(is_restricted, key: 'is_restricted'))
                   .form_param(new_parameter(is_ultra_restricted, key: 'is_ultra_restricted'))
                   .form_param(new_parameter(channel_ids, key: 'channel_ids'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(DefaultSuccessTemplate.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 DefaultErrorTemplateException))
        .execute
    end

    # Invite a user to a workspace.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `admin.users:write`
    # @param [String] team_id Required parameter: The ID (`T1234`) of the
    # workspace.
    # @param [String] email Required parameter: The email address of the person
    # to invite.
    # @param [String] channel_ids Required parameter: A comma-separated list of
    # `channel_id`s for this user to join. At least one channel is required.
    # @param [String] custom_message Optional parameter: An optional message to
    # send to the user in the invite email.
    # @param [String] real_name Optional parameter: Full name of the user.
    # @param [TrueClass | FalseClass] resend Optional parameter: Allow this
    # invite to be resent in the future if a user has not signed up yet.
    # (default: false)
    # @param [TrueClass | FalseClass] is_restricted Optional parameter: Is this
    # user a multi-channel guest user? (default: false)
    # @param [TrueClass | FalseClass] is_ultra_restricted Optional parameter: Is
    # this user a single channel guest user? (default: false)
    # @param [String] guest_expiration_ts Optional parameter: Timestamp when
    # guest account should be disabled. Only include this timestamp if you are
    # inviting a guest user and you want their account to expire on a certain
    # date.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def admin_users_invite(token,
                           team_id,
                           email,
                           channel_ids,
                           custom_message: nil,
                           real_name: nil,
                           resend: nil,
                           is_restricted: nil,
                           is_ultra_restricted: nil,
                           guest_expiration_ts: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/admin.users.invite',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .form_param(new_parameter(team_id, key: 'team_id')
                                .is_required(true))
                   .form_param(new_parameter(email, key: 'email')
                                .is_required(true))
                   .form_param(new_parameter(channel_ids, key: 'channel_ids')
                                .is_required(true))
                   .form_param(new_parameter(custom_message, key: 'custom_message'))
                   .form_param(new_parameter(real_name, key: 'real_name'))
                   .form_param(new_parameter(resend, key: 'resend'))
                   .form_param(new_parameter(is_restricted, key: 'is_restricted'))
                   .form_param(new_parameter(is_ultra_restricted, key: 'is_ultra_restricted'))
                   .form_param(new_parameter(guest_expiration_ts, key: 'guest_expiration_ts'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(DefaultSuccessTemplate.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 DefaultErrorTemplateException))
        .execute
    end

    # List users on a workspace
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `admin.users:read`
    # @param [String] team_id Required parameter: The ID (`T1234`) of the
    # workspace.
    # @param [String] cursor Optional parameter: Set `cursor` to `next_cursor`
    # returned by the previous call to list items in the next page.
    # @param [Integer] limit Optional parameter: Limit for how many users to be
    # retrieved per page
    # @return [ApiResponse] Complete http response with raw body and status code.
    def admin_users_list(token,
                         team_id,
                         cursor: nil,
                         limit: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/admin.users.list',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .query_param(new_parameter(team_id, key: 'team_id')
                                 .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .query_param(new_parameter(cursor, key: 'cursor'))
                   .query_param(new_parameter(limit, key: 'limit'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(DefaultSuccessTemplate.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 DefaultErrorTemplateException))
        .execute
    end

    # Remove a user from a workspace.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `admin.users:write`
    # @param [String] team_id Required parameter: The ID (`T1234`) of the
    # workspace.
    # @param [String] user_id Required parameter: The ID of the user to
    # remove.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def admin_users_remove(token,
                           team_id,
                           user_id)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/admin.users.remove',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .form_param(new_parameter(team_id, key: 'team_id')
                                .is_required(true))
                   .form_param(new_parameter(user_id, key: 'user_id')
                                .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(DefaultSuccessTemplate.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 DefaultErrorTemplateException))
        .execute
    end

    # Set an existing guest, regular user, or owner to be an admin user.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `admin.users:write`
    # @param [String] team_id Required parameter: The ID (`T1234`) of the
    # workspace.
    # @param [String] user_id Required parameter: The ID of the user to
    # designate as an admin.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def admin_users_set_admin(token,
                              team_id,
                              user_id)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/admin.users.setAdmin',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .form_param(new_parameter(team_id, key: 'team_id')
                                .is_required(true))
                   .form_param(new_parameter(user_id, key: 'user_id')
                                .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(DefaultSuccessTemplate.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 DefaultErrorTemplateException))
        .execute
    end

    # Set an expiration for a guest user
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `admin.users:write`
    # @param [String] team_id Required parameter: The ID (`T1234`) of the
    # workspace.
    # @param [String] user_id Required parameter: The ID of the user to set an
    # expiration for.
    # @param [Integer] expiration_ts Required parameter: Timestamp when guest
    # account should be disabled.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def admin_users_set_expiration(token,
                                   team_id,
                                   user_id,
                                   expiration_ts)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/admin.users.setExpiration',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .form_param(new_parameter(team_id, key: 'team_id')
                                .is_required(true))
                   .form_param(new_parameter(user_id, key: 'user_id')
                                .is_required(true))
                   .form_param(new_parameter(expiration_ts, key: 'expiration_ts')
                                .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(DefaultSuccessTemplate.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 DefaultErrorTemplateException))
        .execute
    end

    # Set an existing guest, regular user, or admin user to be a workspace
    # owner.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `admin.users:write`
    # @param [String] team_id Required parameter: The ID (`T1234`) of the
    # workspace.
    # @param [String] user_id Required parameter: Id of the user to promote to
    # owner.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def admin_users_set_owner(token,
                              team_id,
                              user_id)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/admin.users.setOwner',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .form_param(new_parameter(team_id, key: 'team_id')
                                .is_required(true))
                   .form_param(new_parameter(user_id, key: 'user_id')
                                .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(DefaultSuccessTemplate.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 DefaultErrorTemplateException))
        .execute
    end

    # Set an existing guest user, admin user, or owner to be a regular user.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `admin.users:write`
    # @param [String] team_id Required parameter: The ID (`T1234`) of the
    # workspace.
    # @param [String] user_id Required parameter: The ID of the user to
    # designate as a regular user.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def admin_users_set_regular(token,
                                team_id,
                                user_id)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/admin.users.setRegular',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .form_param(new_parameter(team_id, key: 'team_id')
                                .is_required(true))
                   .form_param(new_parameter(user_id, key: 'user_id')
                                .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(DefaultSuccessTemplate.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 DefaultErrorTemplateException))
        .execute
    end
  end
end
