# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # Api
  class Api < BaseApi
    # Checks API calling code.
    # @param [String] error Optional parameter: Error response to return
    # @param [String] foo Optional parameter: example property to return
    # @return [ApiResponse] Complete http response with raw body and status code.
    def api_test(error: nil,
                 foo: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/api.test',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .query_param(new_parameter(error, key: 'error'))
                   .query_param(new_parameter(foo, key: 'foo'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ApiTestSuccessSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Artificial error response',
                                 ApiTestErrorSchemaException))
        .execute
    end
  end
end
