# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # AppsApi
  class AppsApi < BaseApi
    # Uninstalls your app from a workspace.
    # @param [String] token Optional parameter: Authentication token. Requires
    # scope: `none`
    # @param [String] client_id Optional parameter: Issued when you created your
    # application.
    # @param [String] client_secret Optional parameter: Issued when you created
    # your application.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def apps_uninstall(token: nil,
                       client_id: nil,
                       client_secret: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/apps.uninstall',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .query_param(new_parameter(token, key: 'token'))
                   .query_param(new_parameter(client_id, key: 'client_id'))
                   .query_param(new_parameter(client_secret, key: 'client_secret'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(AppsUninstallSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 AppsUninstallErrorSchemaException))
        .execute
    end
  end
end
