# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # AppsPermissionsUsersApi
  class AppsPermissionsUsersApi < BaseApi
    # Returns list of user grants and corresponding scopes this app has on a
    # team.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `none`
    # @param [String] cursor Optional parameter: Paginate through collections of
    # data by setting the `cursor` parameter to a `next_cursor` attribute
    # returned by a previous request's `response_metadata`. Default value
    # fetches the first "page" of the collection. See
    # [pagination](/docs/pagination) for more detail.
    # @param [Integer] limit Optional parameter: The maximum number of items to
    # return.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def apps_permissions_users_list(token,
                                    cursor: nil,
                                    limit: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/apps.permissions.users.list',
                                     Server::DEFAULT)
                   .query_param(new_parameter(token, key: 'token')
                                 .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .query_param(new_parameter(cursor, key: 'cursor'))
                   .query_param(new_parameter(limit, key: 'limit'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(DefaultSuccessTemplate.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 DefaultErrorTemplateException))
        .execute
    end

    # Enables an app to trigger a permissions modal to grant an app access to a
    # user access scope.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `none`
    # @param [String] scopes Required parameter: A comma separated list of user
    # scopes to request for
    # @param [String] trigger_id Required parameter: Token used to trigger the
    # request
    # @param [String] user Required parameter: The user this scope is being
    # requested for
    # @return [ApiResponse] Complete http response with raw body and status code.
    def apps_permissions_users_request(token,
                                       scopes,
                                       trigger_id,
                                       user)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/apps.permissions.users.request',
                                     Server::DEFAULT)
                   .query_param(new_parameter(token, key: 'token')
                                 .is_required(true))
                   .query_param(new_parameter(scopes, key: 'scopes')
                                 .is_required(true))
                   .query_param(new_parameter(trigger_id, key: 'trigger_id')
                                 .is_required(true))
                   .query_param(new_parameter(user, key: 'user')
                                 .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(DefaultSuccessTemplate.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Standard failure response when trigger_id is invalid',
                                 DefaultErrorTemplateException))
        .execute
    end
  end
end
