# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # AppsPermissionsScopesApi
  class AppsPermissionsScopesApi < BaseApi
    # Returns list of scopes this app has on a team.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `none`
    # @return [ApiResponse] Complete http response with raw body and status code.
    def apps_permissions_scopes_list(token)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/apps.permissions.scopes.list',
                                     Server::DEFAULT)
                   .query_param(new_parameter(token, key: 'token')
                                 .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ApiPermissionsScopesListSuccessSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 AppsPermissionsScopesListErrorSchemaException))
        .execute
    end
  end
end
