# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # AppsPermissionsResourcesApi
  class AppsPermissionsResourcesApi < BaseApi
    # Returns list of resource grants this app has on a team.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `none`
    # @param [String] cursor Optional parameter: Paginate through collections of
    # data by setting the `cursor` parameter to a `next_cursor` attribute
    # returned by a previous request's `response_metadata`. Default value
    # fetches the first "page" of the collection. See
    # [pagination](/docs/pagination) for more detail.
    # @param [Integer] limit Optional parameter: The maximum number of items to
    # return.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def apps_permissions_resources_list(token,
                                        cursor: nil,
                                        limit: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/apps.permissions.resources.list',
                                     Server::DEFAULT)
                   .query_param(new_parameter(token, key: 'token')
                                 .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .query_param(new_parameter(cursor, key: 'cursor'))
                   .query_param(new_parameter(limit, key: 'limit'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(AppsPermissionsResourcesListSuccessSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 AppsPermissionsResourcesListErrorSchemaException))
        .execute
    end
  end
end
