# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # ChatApi
  class ChatApi < BaseApi
    # Deletes a message.
    # @param [String] token Optional parameter: Authentication token. Requires
    # scope: `chat:write`
    # @param [Float] ts Optional parameter: Timestamp of the message to be
    # deleted.
    # @param [String] channel Optional parameter: Channel containing the message
    # to be deleted.
    # @param [TrueClass | FalseClass] as_user Optional parameter: Pass true to
    # delete the message as the authed user with `chat:write:user` scope. [Bot
    # users](/bot-users) in this context are considered authed users. If unused
    # or false, the message will be deleted with `chat:write:bot` scope.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def chat_delete(token: nil,
                    ts: nil,
                    channel: nil,
                    as_user: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/chat.delete',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token'))
                   .form_param(new_parameter(ts, key: 'ts'))
                   .form_param(new_parameter(channel, key: 'channel'))
                   .form_param(new_parameter(as_user, key: 'as_user'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ChatDeleteSuccessSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 ChatDeleteErrorSchemaException))
        .execute
    end

    # Deletes a pending scheduled message from the queue.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `chat:write`
    # @param [String] channel Required parameter: The channel the
    # scheduled_message is posting to
    # @param [String] scheduled_message_id Required parameter:
    # `scheduled_message_id` returned from call to chat.scheduleMessage
    # @param [TrueClass | FalseClass] as_user Optional parameter: Pass true to
    # delete the message as the authed user with `chat:write:user` scope. [Bot
    # users](/bot-users) in this context are considered authed users. If unused
    # or false, the message will be deleted with `chat:write:bot` scope.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def chat_delete_scheduled_message(token,
                                      channel,
                                      scheduled_message_id,
                                      as_user: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/chat.deleteScheduledMessage',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .form_param(new_parameter(channel, key: 'channel')
                                .is_required(true))
                   .form_param(new_parameter(scheduled_message_id, key: 'scheduled_message_id')
                                .is_required(true))
                   .form_param(new_parameter(as_user, key: 'as_user'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ChatDeleteScheduledMessageSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response if no message is found',
                                 ChatDeleteScheduledMessageErrorSchemaException))
        .execute
    end

    # Retrieve a permalink URL for a specific extant message
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `none`
    # @param [String] channel Required parameter: The ID of the conversation or
    # channel containing the message
    # @param [String] message_ts Required parameter: A message's `ts` value,
    # uniquely identifying it within a channel
    # @return [ApiResponse] Complete http response with raw body and status code.
    def chat_get_permalink(token,
                           channel,
                           message_ts)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/chat.getPermalink',
                                     Server::DEFAULT)
                   .query_param(new_parameter(token, key: 'token')
                                 .is_required(true))
                   .query_param(new_parameter(channel, key: 'channel')
                                 .is_required(true))
                   .query_param(new_parameter(message_ts, key: 'message_ts')
                                 .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ChatGetPermalinkSuccessSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Error response when channel cannot be found',
                                 ChatGetPermalinkErrorSchemaException))
        .execute
    end

    # Share a me message into a channel.
    # @param [String] token Optional parameter: Authentication token. Requires
    # scope: `chat:write`
    # @param [String] channel Optional parameter: Channel to send message to.
    # Can be a public channel, private group or IM channel. Can be an encoded
    # ID, or a name.
    # @param [String] text Optional parameter: Text of the message to send.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def chat_me_message(token: nil,
                        channel: nil,
                        text: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/chat.meMessage',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token'))
                   .form_param(new_parameter(channel, key: 'channel'))
                   .form_param(new_parameter(text, key: 'text'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ChatMeMessageSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 ChatMeMessageErrorSchemaException))
        .execute
    end

    # Sends an ephemeral message to a user in a channel.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `chat:write`
    # @param [String] channel Required parameter: Channel, private group, or IM
    # channel to send message to. Can be an encoded ID, or a name.
    # @param [String] user Required parameter: `id` of the user who will receive
    # the ephemeral message. The user should be in the channel specified by the
    # `channel` argument.
    # @param [TrueClass | FalseClass] as_user Optional parameter: Pass true to
    # post the message as the authed user. Defaults to true if the
    # chat:write:bot scope is not included. Otherwise, defaults to false.
    # @param [String] attachments Optional parameter: A JSON-based array of
    # structured attachments, presented as a URL-encoded string.
    # @param [String] blocks Optional parameter: A JSON-based array of
    # structured blocks, presented as a URL-encoded string.
    # @param [String] icon_emoji Optional parameter: Emoji to use as the icon
    # for this message. Overrides `icon_url`. Must be used in conjunction with
    # `as_user` set to `false`, otherwise ignored. See [authorship](#authorship)
    # below.
    # @param [String] icon_url Optional parameter: URL to an image to use as the
    # icon for this message. Must be used in conjunction with `as_user` set to
    # false, otherwise ignored. See [authorship](#authorship) below.
    # @param [TrueClass | FalseClass] link_names Optional parameter: Find and
    # link channel names and usernames.
    # @param [String] parse Optional parameter: Change how messages are treated.
    # Defaults to `none`. See [below](#formatting).
    # @param [String] text Optional parameter: How this field works and whether
    # it is required depends on other fields you use in your API call. [See
    # below](#text_usage) for more detail.
    # @param [String] thread_ts Optional parameter: Provide another message's
    # `ts` value to post this message in a thread. Avoid using a reply's `ts`
    # value; use its parent's value instead. Ephemeral messages in threads are
    # only shown if there is already an active thread.
    # @param [String] username Optional parameter: Set your bot's user name.
    # Must be used in conjunction with `as_user` set to false, otherwise
    # ignored. See [authorship](#authorship) below.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def chat_post_ephemeral(token,
                            channel,
                            user,
                            as_user: nil,
                            attachments: nil,
                            blocks: nil,
                            icon_emoji: nil,
                            icon_url: nil,
                            link_names: nil,
                            parse: nil,
                            text: nil,
                            thread_ts: nil,
                            username: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/chat.postEphemeral',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .form_param(new_parameter(channel, key: 'channel')
                                .is_required(true))
                   .form_param(new_parameter(user, key: 'user')
                                .is_required(true))
                   .form_param(new_parameter(as_user, key: 'as_user'))
                   .form_param(new_parameter(attachments, key: 'attachments'))
                   .form_param(new_parameter(blocks, key: 'blocks'))
                   .form_param(new_parameter(icon_emoji, key: 'icon_emoji'))
                   .form_param(new_parameter(icon_url, key: 'icon_url'))
                   .form_param(new_parameter(link_names, key: 'link_names'))
                   .form_param(new_parameter(parse, key: 'parse'))
                   .form_param(new_parameter(text, key: 'text'))
                   .form_param(new_parameter(thread_ts, key: 'thread_ts'))
                   .form_param(new_parameter(username, key: 'username'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ChatPostEphemeralSuccessSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 ChatPostEphemeralErrorSchemaException))
        .execute
    end

    # Sends a message to a channel.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `chat:write`
    # @param [String] channel Required parameter: Channel, private group, or IM
    # channel to send message to. Can be an encoded ID, or a name. See
    # [below](#channels) for more details.
    # @param [String] as_user Optional parameter: Pass true to post the message
    # as the authed user, instead of as a bot. Defaults to false. See
    # [authorship](#authorship) below.
    # @param [String] attachments Optional parameter: A JSON-based array of
    # structured attachments, presented as a URL-encoded string.
    # @param [String] blocks Optional parameter: A JSON-based array of
    # structured blocks, presented as a URL-encoded string.
    # @param [String] icon_emoji Optional parameter: Emoji to use as the icon
    # for this message. Overrides `icon_url`. Must be used in conjunction with
    # `as_user` set to `false`, otherwise ignored. See [authorship](#authorship)
    # below.
    # @param [String] icon_url Optional parameter: URL to an image to use as the
    # icon for this message. Must be used in conjunction with `as_user` set to
    # false, otherwise ignored. See [authorship](#authorship) below.
    # @param [TrueClass | FalseClass] link_names Optional parameter: Find and
    # link channel names and usernames.
    # @param [TrueClass | FalseClass] mrkdwn Optional parameter: Disable Slack
    # markup parsing by setting to `false`. Enabled by default.
    # @param [String] parse Optional parameter: Change how messages are treated.
    # Defaults to `none`. See [below](#formatting).
    # @param [TrueClass | FalseClass] reply_broadcast Optional parameter: Used
    # in conjunction with `thread_ts` and indicates whether reply should be made
    # visible to everyone in the channel or conversation. Defaults to `false`.
    # @param [String] text Optional parameter: How this field works and whether
    # it is required depends on other fields you use in your API call. [See
    # below](#text_usage) for more detail.
    # @param [String] thread_ts Optional parameter: Provide another message's
    # `ts` value to make this message a reply. Avoid using a reply's `ts` value;
    # use its parent instead.
    # @param [TrueClass | FalseClass] unfurl_links Optional parameter: Pass true
    # to enable unfurling of primarily text-based content.
    # @param [TrueClass | FalseClass] unfurl_media Optional parameter: Pass
    # false to disable unfurling of media content.
    # @param [String] username Optional parameter: Set your bot's user name.
    # Must be used in conjunction with `as_user` set to false, otherwise
    # ignored. See [authorship](#authorship) below.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def chat_post_message(token,
                          channel,
                          as_user: nil,
                          attachments: nil,
                          blocks: nil,
                          icon_emoji: nil,
                          icon_url: nil,
                          link_names: nil,
                          mrkdwn: nil,
                          parse: nil,
                          reply_broadcast: nil,
                          text: nil,
                          thread_ts: nil,
                          unfurl_links: nil,
                          unfurl_media: nil,
                          username: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/chat.postMessage',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .form_param(new_parameter(channel, key: 'channel')
                                .is_required(true))
                   .form_param(new_parameter(as_user, key: 'as_user'))
                   .form_param(new_parameter(attachments, key: 'attachments'))
                   .form_param(new_parameter(blocks, key: 'blocks'))
                   .form_param(new_parameter(icon_emoji, key: 'icon_emoji'))
                   .form_param(new_parameter(icon_url, key: 'icon_url'))
                   .form_param(new_parameter(link_names, key: 'link_names'))
                   .form_param(new_parameter(mrkdwn, key: 'mrkdwn'))
                   .form_param(new_parameter(parse, key: 'parse'))
                   .form_param(new_parameter(reply_broadcast, key: 'reply_broadcast'))
                   .form_param(new_parameter(text, key: 'text'))
                   .form_param(new_parameter(thread_ts, key: 'thread_ts'))
                   .form_param(new_parameter(unfurl_links, key: 'unfurl_links'))
                   .form_param(new_parameter(unfurl_media, key: 'unfurl_media'))
                   .form_param(new_parameter(username, key: 'username'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ChatPostMessageSuccessSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response if too many attachments are included',
                                 ChatPostMessageErrorSchemaException))
        .execute
    end

    # Schedules a message to be sent to a channel.
    # @param [String] token Optional parameter: Authentication token. Requires
    # scope: `chat:write`
    # @param [String] channel Optional parameter: Channel, private group, or DM
    # channel to send message to. Can be an encoded ID, or a name. See
    # [below](#channels) for more details.
    # @param [String] text Optional parameter: How this field works and whether
    # it is required depends on other fields you use in your API call. [See
    # below](#text_usage) for more detail.
    # @param [String] post_at Optional parameter: Unix EPOCH timestamp of time
    # in future to send the message.
    # @param [String] parse Optional parameter: Change how messages are treated.
    # Defaults to `none`. See [chat.postMessage](chat.postMessage#formatting).
    # @param [TrueClass | FalseClass] as_user Optional parameter: Pass true to
    # post the message as the authed user, instead of as a bot. Defaults to
    # false. See [chat.postMessage](chat.postMessage#authorship).
    # @param [TrueClass | FalseClass] link_names Optional parameter: Find and
    # link channel names and usernames.
    # @param [String] attachments Optional parameter: A JSON-based array of
    # structured attachments, presented as a URL-encoded string.
    # @param [String] blocks Optional parameter: A JSON-based array of
    # structured blocks, presented as a URL-encoded string.
    # @param [TrueClass | FalseClass] unfurl_links Optional parameter: Pass true
    # to enable unfurling of primarily text-based content.
    # @param [TrueClass | FalseClass] unfurl_media Optional parameter: Pass
    # false to disable unfurling of media content.
    # @param [Float] thread_ts Optional parameter: Provide another message's
    # `ts` value to make this message a reply. Avoid using a reply's `ts` value;
    # use its parent instead.
    # @param [TrueClass | FalseClass] reply_broadcast Optional parameter: Used
    # in conjunction with `thread_ts` and indicates whether reply should be made
    # visible to everyone in the channel or conversation. Defaults to `false`.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def chat_schedule_message(token: nil,
                              channel: nil,
                              text: nil,
                              post_at: nil,
                              parse: nil,
                              as_user: nil,
                              link_names: nil,
                              attachments: nil,
                              blocks: nil,
                              unfurl_links: nil,
                              unfurl_media: nil,
                              thread_ts: nil,
                              reply_broadcast: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/chat.scheduleMessage',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token'))
                   .form_param(new_parameter(channel, key: 'channel'))
                   .form_param(new_parameter(text, key: 'text'))
                   .form_param(new_parameter(post_at, key: 'post_at'))
                   .form_param(new_parameter(parse, key: 'parse'))
                   .form_param(new_parameter(as_user, key: 'as_user'))
                   .form_param(new_parameter(link_names, key: 'link_names'))
                   .form_param(new_parameter(attachments, key: 'attachments'))
                   .form_param(new_parameter(blocks, key: 'blocks'))
                   .form_param(new_parameter(unfurl_links, key: 'unfurl_links'))
                   .form_param(new_parameter(unfurl_media, key: 'unfurl_media'))
                   .form_param(new_parameter(thread_ts, key: 'thread_ts'))
                   .form_param(new_parameter(reply_broadcast, key: 'reply_broadcast'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ChatScheduleMessageSuccessSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response if the `post_at` is invalid (ex. in the'\
                                  ' past or too far into the future)',
                                 ChatScheduleMessageErrorSchemaException))
        .execute
    end

    # Provide custom unfurl behavior for user-posted URLs
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `links:write`
    # @param [String] channel Required parameter: Channel ID of the message
    # @param [String] ts Required parameter: Timestamp of the message to add
    # unfurl behavior to.
    # @param [String] unfurls Optional parameter: URL-encoded JSON map with keys
    # set to URLs featured in the the message, pointing to their unfurl blocks
    # or message attachments.
    # @param [String] user_auth_message Optional parameter: Provide a
    # simply-formatted string to send as an ephemeral message to the user as
    # invitation to authenticate further and enable full unfurling behavior
    # @param [TrueClass | FalseClass] user_auth_required Optional parameter: Set
    # to `true` or `1` to indicate the user must install your Slack app to
    # trigger unfurls for this domain
    # @param [String] user_auth_url Optional parameter: Send users to this
    # custom URL where they will complete authentication in your app to fully
    # trigger unfurling. Value should be properly URL-encoded.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def chat_unfurl(token,
                    channel,
                    ts,
                    unfurls: nil,
                    user_auth_message: nil,
                    user_auth_required: nil,
                    user_auth_url: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/chat.unfurl',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .form_param(new_parameter(channel, key: 'channel')
                                .is_required(true))
                   .form_param(new_parameter(ts, key: 'ts')
                                .is_required(true))
                   .form_param(new_parameter(unfurls, key: 'unfurls'))
                   .form_param(new_parameter(user_auth_message, key: 'user_auth_message'))
                   .form_param(new_parameter(user_auth_required, key: 'user_auth_required'))
                   .form_param(new_parameter(user_auth_url, key: 'user_auth_url'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ChatUnfurlSuccessSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 ChatUnfurlErrorSchemaException))
        .execute
    end

    # Updates a message.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `chat:write`
    # @param [String] channel Required parameter: Channel containing the message
    # to be updated.
    # @param [String] ts Required parameter: Timestamp of the message to be
    # updated.
    # @param [String] as_user Optional parameter: Pass true to update the
    # message as the authed user. [Bot users](/bot-users) in this context are
    # considered authed users.
    # @param [String] attachments Optional parameter: A JSON-based array of
    # structured attachments, presented as a URL-encoded string. This field is
    # required when not presenting `text`. If you don't include this field, the
    # message's previous `attachments` will be retained. To remove previous
    # `attachments`, include an empty array for this field.
    # @param [String] blocks Optional parameter: A JSON-based array of
    # [structured blocks](/block-kit/building), presented as a URL-encoded
    # string. If you don't include this field, the message's previous `blocks`
    # will be retained. To remove previous `blocks`, include an empty array for
    # this field.
    # @param [String] link_names Optional parameter: Find and link channel names
    # and usernames. Defaults to `none`. If you do not specify a value for this
    # field, the original value set for the message will be overwritten with the
    # default, `none`.
    # @param [String] parse Optional parameter: Change how messages are treated.
    # Defaults to `client`, unlike `chat.postMessage`. Accepts either `none` or
    # `full`. If you do not specify a value for this field, the original value
    # set for the message will be overwritten with the default, `client`.
    # @param [String] text Optional parameter: New text for the message, using
    # the [default formatting rules](/reference/surfaces/formatting). It's not
    # required when presenting `blocks` or `attachments`.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def chat_update(token,
                    channel,
                    ts,
                    as_user: nil,
                    attachments: nil,
                    blocks: nil,
                    link_names: nil,
                    parse: nil,
                    text: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/chat.update',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .form_param(new_parameter(channel, key: 'channel')
                                .is_required(true))
                   .form_param(new_parameter(ts, key: 'ts')
                                .is_required(true))
                   .form_param(new_parameter(as_user, key: 'as_user'))
                   .form_param(new_parameter(attachments, key: 'attachments'))
                   .form_param(new_parameter(blocks, key: 'blocks'))
                   .form_param(new_parameter(link_names, key: 'link_names'))
                   .form_param(new_parameter(parse, key: 'parse'))
                   .form_param(new_parameter(text, key: 'text'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ChatUpdateSuccessSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 ChatUpdateErrorSchemaException))
        .execute
    end
  end
end
