# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # DialogApi
  class DialogApi < BaseApi
    # Open a dialog with a user
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `none`
    # @param [String] dialog Required parameter: The dialog definition. This
    # must be a JSON-encoded string.
    # @param [String] trigger_id Required parameter: Exchange a trigger to post
    # to the user.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def dialog_open(token,
                    dialog,
                    trigger_id)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/dialog.open',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .query_param(new_parameter(dialog, key: 'dialog')
                                 .is_required(true))
                   .query_param(new_parameter(trigger_id, key: 'trigger_id')
                                 .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(DialogOpenSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response, before getting to any possible'\
                                  ' validation errors.',
                                 DialogOpenErrorSchemaException))
        .execute
    end
  end
end
