# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # FilesCommentsApi
  class FilesCommentsApi < BaseApi
    # Deletes an existing comment on a file.
    # @param [String] token Optional parameter: Authentication token. Requires
    # scope: `files:write:user`
    # @param [String] file Optional parameter: File to delete a comment from.
    # @param [String] id Optional parameter: The comment to delete.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def files_comments_delete(token: nil,
                              file: nil,
                              id: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/files.comments.delete',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token'))
                   .form_param(new_parameter(file, key: 'file'))
                   .form_param(new_parameter(id, key: 'id'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(FilesCommentsDeleteSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Standard failure response when used with an invalid token',
                                 FilesCommentsDeleteErrorSchemaException))
        .execute
    end
  end
end
