# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # OauthV2Api
  class OauthV2Api < BaseApi
    # Exchanges a temporary OAuth verifier code for an access token.
    # @param [String] code Required parameter: The `code` param returned via the
    # OAuth callback.
    # @param [String] client_id Optional parameter: Issued when you created your
    # application.
    # @param [String] client_secret Optional parameter: Issued when you created
    # your application.
    # @param [String] redirect_uri Optional parameter: This must match the
    # originally submitted URI (if one was sent).
    # @return [ApiResponse] Complete http response with raw body and status code.
    def oauth_v2_access(code,
                        client_id: nil,
                        client_secret: nil,
                        redirect_uri: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/oauth.v2.access',
                                     Server::DEFAULT)
                   .query_param(new_parameter(code, key: 'code')
                                 .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .query_param(new_parameter(client_id, key: 'client_id'))
                   .query_param(new_parameter(client_secret, key: 'client_secret'))
                   .query_param(new_parameter(redirect_uri, key: 'redirect_uri'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(DefaultSuccessTemplate.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 DefaultErrorTemplateException))
        .execute
    end
  end
end
