# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # PinsApi
  class PinsApi < BaseApi
    # Pins an item to a channel.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `pins:write`
    # @param [String] channel Required parameter: Channel to pin the item in.
    # @param [String] timestamp Optional parameter: Timestamp of the message to
    # pin.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def pins_add(token,
                 channel,
                 timestamp: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/pins.add',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .form_param(new_parameter(channel, key: 'channel')
                                .is_required(true))
                   .form_param(new_parameter(timestamp, key: 'timestamp'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(PinsAddSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 PinsAddErrorSchemaException))
        .execute
    end

    # Lists items pinned to a channel.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `pins:read`
    # @param [String] channel Required parameter: Channel to get pinned items
    # for.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def pins_list(token,
                  channel)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/pins.list',
                                     Server::DEFAULT)
                   .query_param(new_parameter(token, key: 'token')
                                 .is_required(true))
                   .query_param(new_parameter(channel, key: 'channel')
                                 .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:dynamic_deserializer))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 PinsListErrorSchemaException))
        .execute
    end

    # Un-pins an item from a channel.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `pins:write`
    # @param [String] channel Required parameter: Channel where the item is
    # pinned to.
    # @param [String] timestamp Optional parameter: Timestamp of the message to
    # un-pin.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def pins_remove(token,
                    channel,
                    timestamp: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/pins.remove',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .form_param(new_parameter(channel, key: 'channel')
                                .is_required(true))
                   .form_param(new_parameter(timestamp, key: 'timestamp'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(PinsRemoveSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 PinsRemoveErrorSchemaException))
        .execute
    end
  end
end
