# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # ReactionsApi
  class ReactionsApi < BaseApi
    # Adds a reaction to an item.
    # @param [String] channel Required parameter: Channel where the message to
    # add reaction to was posted.
    # @param [String] name Required parameter: Reaction (emoji) name.
    # @param [String] timestamp Required parameter: Timestamp of the message to
    # add reaction to.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `reactions:write`
    # @return [ApiResponse] Complete http response with raw body and status code.
    def reactions_add(channel,
                      name,
                      timestamp,
                      token)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/reactions.add',
                                     Server::DEFAULT)
                   .form_param(new_parameter(channel, key: 'channel')
                                .is_required(true))
                   .form_param(new_parameter(name, key: 'name')
                                .is_required(true))
                   .form_param(new_parameter(timestamp, key: 'timestamp')
                                .is_required(true))
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ReactionsAddSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 ReactionsAddErrorSchemaException))
        .execute
    end

    # Gets reactions for an item.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `reactions:read`
    # @param [String] channel Optional parameter: Channel where the message to
    # get reactions for was posted.
    # @param [String] file Optional parameter: File to get reactions for.
    # @param [String] file_comment Optional parameter: File comment to get
    # reactions for.
    # @param [TrueClass | FalseClass] full Optional parameter: If true always
    # return the complete reaction list.
    # @param [String] timestamp Optional parameter: Timestamp of the message to
    # get reactions for.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def reactions_get(token,
                      channel: nil,
                      file: nil,
                      file_comment: nil,
                      full: nil,
                      timestamp: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/reactions.get',
                                     Server::DEFAULT)
                   .query_param(new_parameter(token, key: 'token')
                                 .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .query_param(new_parameter(channel, key: 'channel'))
                   .query_param(new_parameter(file, key: 'file'))
                   .query_param(new_parameter(file_comment, key: 'file_comment'))
                   .query_param(new_parameter(full, key: 'full'))
                   .query_param(new_parameter(timestamp, key: 'timestamp'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:json_deserialize))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 ReactionsGetErrorSchemaException))
        .execute
    end

    # Lists reactions made by a user.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `reactions:read`
    # @param [String] user Optional parameter: Show reactions made by this user.
    # Defaults to the authed user.
    # @param [TrueClass | FalseClass] full Optional parameter: If true always
    # return the complete reaction list.
    # @param [Integer] count Optional parameter: TODO: type description here
    # @param [Integer] page Optional parameter: TODO: type description here
    # @param [String] cursor Optional parameter: Parameter for pagination. Set
    # `cursor` equal to the `next_cursor` attribute returned by the previous
    # request's `response_metadata`. This parameter is optional, but pagination
    # is mandatory: the default value simply fetches the first "page" of the
    # collection.
    # @param [Integer] limit Optional parameter: The maximum number of items to
    # return. Fewer than the requested number of items may be returned, even if
    # the end of the list hasn't been reached.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def reactions_list(token,
                       user: nil,
                       full: nil,
                       count: nil,
                       page: nil,
                       cursor: nil,
                       limit: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/reactions.list',
                                     Server::DEFAULT)
                   .query_param(new_parameter(token, key: 'token')
                                 .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .query_param(new_parameter(user, key: 'user'))
                   .query_param(new_parameter(full, key: 'full'))
                   .query_param(new_parameter(count, key: 'count'))
                   .query_param(new_parameter(page, key: 'page'))
                   .query_param(new_parameter(cursor, key: 'cursor'))
                   .query_param(new_parameter(limit, key: 'limit'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ReactionsListSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 ReactionsListErrorSchemaException))
        .execute
    end

    # Removes a reaction from an item.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `reactions:write`
    # @param [String] name Required parameter: Reaction (emoji) name.
    # @param [String] file Optional parameter: File to remove reaction from.
    # @param [String] file_comment Optional parameter: File comment to remove
    # reaction from.
    # @param [String] channel Optional parameter: Channel where the message to
    # remove reaction from was posted.
    # @param [String] timestamp Optional parameter: Timestamp of the message to
    # remove reaction from.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def reactions_remove(token,
                         name,
                         file: nil,
                         file_comment: nil,
                         channel: nil,
                         timestamp: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/reactions.remove',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .form_param(new_parameter(name, key: 'name')
                                .is_required(true))
                   .form_param(new_parameter(file, key: 'file'))
                   .form_param(new_parameter(file_comment, key: 'file_comment'))
                   .form_param(new_parameter(channel, key: 'channel'))
                   .form_param(new_parameter(timestamp, key: 'timestamp'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ReactionsRemoveSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 ReactionsRemoveErrorSchemaException))
        .execute
    end
  end
end
