# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # RemindersApi
  class RemindersApi < BaseApi
    # Creates a reminder.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `reminders:write`
    # @param [String] text Required parameter: The content of the reminder
    # @param [String] time Required parameter: When this reminder should happen:
    # the Unix timestamp (up to five years from now), the number of seconds
    # until the reminder (if within 24 hours), or a natural language description
    # (Ex. "in 15 minutes," or "every Thursday")
    # @param [String] user Optional parameter: The user who will receive the
    # reminder. If no user is specified, the reminder will go to user who
    # created it.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def reminders_add(token,
                      text,
                      time,
                      user: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/reminders.add',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .form_param(new_parameter(text, key: 'text')
                                .is_required(true))
                   .form_param(new_parameter(time, key: 'time')
                                .is_required(true))
                   .form_param(new_parameter(user, key: 'user'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(RemindersAddSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 RemindersAddErrorSchemaException))
        .execute
    end

    # Marks a reminder as complete.
    # @param [String] token Optional parameter: Authentication token. Requires
    # scope: `reminders:write`
    # @param [String] reminder Optional parameter: The ID of the reminder to be
    # marked as complete
    # @return [ApiResponse] Complete http response with raw body and status code.
    def reminders_complete(token: nil,
                           reminder: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/reminders.complete',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token'))
                   .form_param(new_parameter(reminder, key: 'reminder'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(RemindersCompleteSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 RemindersCompleteErrorSchemaException))
        .execute
    end

    # Deletes a reminder.
    # @param [String] token Optional parameter: Authentication token. Requires
    # scope: `reminders:write`
    # @param [String] reminder Optional parameter: The ID of the reminder
    # @return [ApiResponse] Complete http response with raw body and status code.
    def reminders_delete(token: nil,
                         reminder: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/reminders.delete',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token'))
                   .form_param(new_parameter(reminder, key: 'reminder'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(RemindersDeleteSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 RemindersDeleteErrorSchemaException))
        .execute
    end

    # Gets information about a reminder.
    # @param [String] token Optional parameter: Authentication token. Requires
    # scope: `reminders:read`
    # @param [String] reminder Optional parameter: The ID of the reminder
    # @return [ApiResponse] Complete http response with raw body and status code.
    def reminders_info(token: nil,
                       reminder: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/reminders.info',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .query_param(new_parameter(token, key: 'token'))
                   .query_param(new_parameter(reminder, key: 'reminder'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(RemindersInfoSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 RemindersInfoErrorSchemaException))
        .execute
    end

    # Lists all reminders created by or for a given user.
    # @param [String] token Optional parameter: Authentication token. Requires
    # scope: `reminders:read`
    # @return [ApiResponse] Complete http response with raw body and status code.
    def reminders_list(token: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/reminders.list',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .query_param(new_parameter(token, key: 'token'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(RemindersListSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 RemindersListErrorSchemaException))
        .execute
    end
  end
end
