# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # RtmApi
  class RtmApi < BaseApi
    # Starts a Real Time Messaging session.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `rtm:stream`
    # @param [TrueClass | FalseClass] batch_presence_aware Optional parameter:
    # Batch presence deliveries via subscription. Enabling changes the shape of
    # `presence_change` events.
    # @param [TrueClass | FalseClass] presence_sub Optional parameter: Only
    # deliver presence events when requested by subscription
    # @return [ApiResponse] Complete http response with raw body and status code.
    def rtm_connect(token,
                    batch_presence_aware: nil,
                    presence_sub: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/rtm.connect',
                                     Server::DEFAULT)
                   .query_param(new_parameter(token, key: 'token')
                                 .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .query_param(new_parameter(batch_presence_aware, key: 'batch_presence_aware'))
                   .query_param(new_parameter(presence_sub, key: 'presence_sub'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(RtmConnectSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 RtmConnectErrorSchemaException))
        .execute
    end
  end
end
