# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # StarsApi
  class StarsApi < BaseApi
    # Adds a star to an item.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `stars:write`
    # @param [String] channel Optional parameter: Channel to add star to, or
    # channel where the message to add star to was posted (used with
    # `timestamp`).
    # @param [String] file Optional parameter: File to add star to.
    # @param [String] file_comment Optional parameter: File comment to add star
    # to.
    # @param [String] timestamp Optional parameter: Timestamp of the message to
    # add star to.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def stars_add(token,
                  channel: nil,
                  file: nil,
                  file_comment: nil,
                  timestamp: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/stars.add',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .form_param(new_parameter(channel, key: 'channel'))
                   .form_param(new_parameter(file, key: 'file'))
                   .form_param(new_parameter(file_comment, key: 'file_comment'))
                   .form_param(new_parameter(timestamp, key: 'timestamp'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(StarsAddSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 StarsAddErrorSchemaException))
        .execute
    end

    # Lists stars for a user.
    # @param [String] token Optional parameter: Authentication token. Requires
    # scope: `stars:read`
    # @param [String] count Optional parameter: TODO: type description here
    # @param [String] page Optional parameter: TODO: type description here
    # @param [String] cursor Optional parameter: Parameter for pagination. Set
    # `cursor` equal to the `next_cursor` attribute returned by the previous
    # request's `response_metadata`. This parameter is optional, but pagination
    # is mandatory: the default value simply fetches the first "page" of the
    # collection.
    # @param [Integer] limit Optional parameter: The maximum number of items to
    # return. Fewer than the requested number of items may be returned, even if
    # the end of the list hasn't been reached.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def stars_list(token: nil,
                   count: nil,
                   page: nil,
                   cursor: nil,
                   limit: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/stars.list',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .query_param(new_parameter(token, key: 'token'))
                   .query_param(new_parameter(count, key: 'count'))
                   .query_param(new_parameter(page, key: 'page'))
                   .query_param(new_parameter(cursor, key: 'cursor'))
                   .query_param(new_parameter(limit, key: 'limit'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(StarsListSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 StarsListErrorSchemaException))
        .execute
    end

    # Removes a star from an item.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `stars:write`
    # @param [String] channel Optional parameter: Channel to remove star from,
    # or channel where the message to remove star from was posted (used with
    # `timestamp`).
    # @param [String] file Optional parameter: File to remove star from.
    # @param [String] file_comment Optional parameter: File comment to remove
    # star from.
    # @param [String] timestamp Optional parameter: Timestamp of the message to
    # remove star from.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def stars_remove(token,
                     channel: nil,
                     file: nil,
                     file_comment: nil,
                     timestamp: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/stars.remove',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .form_param(new_parameter(channel, key: 'channel'))
                   .form_param(new_parameter(file, key: 'file'))
                   .form_param(new_parameter(file_comment, key: 'file_comment'))
                   .form_param(new_parameter(timestamp, key: 'timestamp'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(StarsRemoveSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 StarsRemoveErrorSchemaException))
        .execute
    end
  end
end
