# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # TeamProfileApi
  class TeamProfileApi < BaseApi
    # Retrieve a team's profile.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `users.profile:read`
    # @param [String] visibility Optional parameter: Filter by visibility.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def team_profile_get(token,
                         visibility: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/team.profile.get',
                                     Server::DEFAULT)
                   .query_param(new_parameter(token, key: 'token')
                                 .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .query_param(new_parameter(visibility, key: 'visibility'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(TeamProfileGetSuccessSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 TeamProfileGetErrorSchemaException))
        .execute
    end
  end
end
