# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # TeamApi
  class TeamApi < BaseApi
    # Gets the access logs for the current team.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `admin`
    # @param [String] before Optional parameter: End of time range of logs to
    # include in results (inclusive).
    # @param [String] count Optional parameter: TODO: type description here
    # @param [String] page Optional parameter: TODO: type description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def team_access_logs(token,
                         before: nil,
                         count: nil,
                         page: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/team.accessLogs',
                                     Server::DEFAULT)
                   .query_param(new_parameter(token, key: 'token')
                                 .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .query_param(new_parameter(before, key: 'before'))
                   .query_param(new_parameter(count, key: 'count'))
                   .query_param(new_parameter(page, key: 'page'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(TeamAccessLogsSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'A workspace must be on a paid plan to use this method,'\
                                  ' otherwise the `paid_only` error is thrown:',
                                 TeamAccessLogsErrorSchemaException))
        .execute
    end

    # Gets billable users information for the current team.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `admin`
    # @param [String] user Optional parameter: A user to retrieve the billable
    # information for. Defaults to all users.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def team_billable_info(token,
                           user: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/team.billableInfo',
                                     Server::DEFAULT)
                   .query_param(new_parameter(token, key: 'token')
                                 .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .query_param(new_parameter(user, key: 'user'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(DefaultSuccessTemplate.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 DefaultErrorTemplateException))
        .execute
    end

    # Gets information about the current team.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `team:read`
    # @param [String] team Optional parameter: Team to get info on, if omitted,
    # will return information about the current team. Will only return team that
    # the authenticated token is allowed to see through external shared
    # channels
    # @return [ApiResponse] Complete http response with raw body and status code.
    def team_info(token,
                  team: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/team.info',
                                     Server::DEFAULT)
                   .query_param(new_parameter(token, key: 'token')
                                 .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .query_param(new_parameter(team, key: 'team'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(TeamInfoSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 TeamInfoErrorSchemaException))
        .execute
    end

    # Gets the integration logs for the current team.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `admin`
    # @param [String] app_id Optional parameter: Filter logs to this Slack app.
    # Defaults to all logs.
    # @param [String] change_type Optional parameter: Filter logs with this
    # change type. Defaults to all logs.
    # @param [String] count Optional parameter: TODO: type description here
    # @param [String] page Optional parameter: TODO: type description here
    # @param [String] service_id Optional parameter: Filter logs to this
    # service. Defaults to all logs.
    # @param [String] user Optional parameter: Filter logs generated by this
    # user’s actions. Defaults to all logs.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def team_integration_logs(token,
                              app_id: nil,
                              change_type: nil,
                              count: nil,
                              page: nil,
                              service_id: nil,
                              user: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/team.integrationLogs',
                                     Server::DEFAULT)
                   .query_param(new_parameter(token, key: 'token')
                                 .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .query_param(new_parameter(app_id, key: 'app_id'))
                   .query_param(new_parameter(change_type, key: 'change_type'))
                   .query_param(new_parameter(count, key: 'count'))
                   .query_param(new_parameter(page, key: 'page'))
                   .query_param(new_parameter(service_id, key: 'service_id'))
                   .query_param(new_parameter(user, key: 'user'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(TeamIntegrationLogsSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 TeamIntegrationLogsErrorSchemaException))
        .execute
    end
  end
end
