# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # UsergroupsApi
  class UsergroupsApi < BaseApi
    # Create a User Group
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `usergroups:write`
    # @param [String] name Required parameter: A name for the User Group. Must
    # be unique among User Groups.
    # @param [String] channels Optional parameter: A comma separated string of
    # encoded channel IDs for which the User Group uses as a default.
    # @param [String] description Optional parameter: A short description of the
    # User Group.
    # @param [String] handle Optional parameter: A mention handle. Must be
    # unique among channels, users and User Groups.
    # @param [TrueClass | FalseClass] include_count Optional parameter: Include
    # the number of users in each User Group.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def usergroups_create(token,
                          name,
                          channels: nil,
                          description: nil,
                          handle: nil,
                          include_count: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/usergroups.create',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .form_param(new_parameter(name, key: 'name')
                                .is_required(true))
                   .form_param(new_parameter(channels, key: 'channels'))
                   .form_param(new_parameter(description, key: 'description'))
                   .form_param(new_parameter(handle, key: 'handle'))
                   .form_param(new_parameter(include_count, key: 'include_count'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(UsergroupsCreateSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 UsergroupsCreateErrorSchemaException))
        .execute
    end

    # Disable an existing User Group
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `usergroups:write`
    # @param [String] usergroup Required parameter: The encoded ID of the User
    # Group to disable.
    # @param [TrueClass | FalseClass] include_count Optional parameter: Include
    # the number of users in the User Group.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def usergroups_disable(token,
                           usergroup,
                           include_count: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/usergroups.disable',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .form_param(new_parameter(usergroup, key: 'usergroup')
                                .is_required(true))
                   .form_param(new_parameter(include_count, key: 'include_count'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(UsergroupsDisableSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 UsergroupsDisableErrorSchemaException))
        .execute
    end

    # Enable a User Group
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `usergroups:write`
    # @param [String] usergroup Required parameter: The encoded ID of the User
    # Group to enable.
    # @param [TrueClass | FalseClass] include_count Optional parameter: Include
    # the number of users in the User Group.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def usergroups_enable(token,
                          usergroup,
                          include_count: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/usergroups.enable',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .form_param(new_parameter(usergroup, key: 'usergroup')
                                .is_required(true))
                   .form_param(new_parameter(include_count, key: 'include_count'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(UsergroupsEnableSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 UsergroupsEnableErrorSchemaException))
        .execute
    end

    # List all User Groups for a team
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `usergroups:read`
    # @param [TrueClass | FalseClass] include_users Optional parameter: Include
    # the list of users for each User Group.
    # @param [TrueClass | FalseClass] include_count Optional parameter: Include
    # the number of users in each User Group.
    # @param [TrueClass | FalseClass] include_disabled Optional parameter:
    # Include disabled User Groups.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def usergroups_list(token,
                        include_users: nil,
                        include_count: nil,
                        include_disabled: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/usergroups.list',
                                     Server::DEFAULT)
                   .query_param(new_parameter(token, key: 'token')
                                 .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .query_param(new_parameter(include_users, key: 'include_users'))
                   .query_param(new_parameter(include_count, key: 'include_count'))
                   .query_param(new_parameter(include_disabled, key: 'include_disabled'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(UsergroupsListSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 UsergroupsListErrorSchemaException))
        .execute
    end

    # Update an existing User Group
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `usergroups:write`
    # @param [String] usergroup Required parameter: The encoded ID of the User
    # Group to update.
    # @param [String] handle Optional parameter: A mention handle. Must be
    # unique among channels, users and User Groups.
    # @param [String] description Optional parameter: A short description of the
    # User Group.
    # @param [String] channels Optional parameter: A comma separated string of
    # encoded channel IDs for which the User Group uses as a default.
    # @param [TrueClass | FalseClass] include_count Optional parameter: Include
    # the number of users in the User Group.
    # @param [String] name Optional parameter: A name for the User Group. Must
    # be unique among User Groups.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def usergroups_update(token,
                          usergroup,
                          handle: nil,
                          description: nil,
                          channels: nil,
                          include_count: nil,
                          name: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/usergroups.update',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .form_param(new_parameter(usergroup, key: 'usergroup')
                                .is_required(true))
                   .form_param(new_parameter(handle, key: 'handle'))
                   .form_param(new_parameter(description, key: 'description'))
                   .form_param(new_parameter(channels, key: 'channels'))
                   .form_param(new_parameter(include_count, key: 'include_count'))
                   .form_param(new_parameter(name, key: 'name'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(UsergroupsUpdateSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 UsergroupsUpdateErrorSchemaException))
        .execute
    end
  end
end
