# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # UsersApi
  class UsersApi < BaseApi
    # List conversations the calling user may access.
    # @param [String] token Optional parameter: Authentication token. Requires
    # scope: `conversations:read`
    # @param [String] user Optional parameter: Browse conversations by a
    # specific user ID's membership. Non-public channels are restricted to those
    # where the calling user shares membership.
    # @param [String] types Optional parameter: Mix and match channel types by
    # providing a comma-separated list of any combination of `public_channel`,
    # `private_channel`, `mpim`, `im`
    # @param [TrueClass | FalseClass] exclude_archived Optional parameter: Set
    # to `true` to exclude archived channels from the list
    # @param [Integer] limit Optional parameter: The maximum number of items to
    # return. Fewer than the requested number of items may be returned, even if
    # the end of the list hasn't been reached. Must be an integer no larger than
    # 1000.
    # @param [String] cursor Optional parameter: Paginate through collections of
    # data by setting the `cursor` parameter to a `next_cursor` attribute
    # returned by a previous request's `response_metadata`. Default value
    # fetches the first "page" of the collection.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def users_conversations(token: nil,
                            user: nil,
                            types: nil,
                            exclude_archived: nil,
                            limit: nil,
                            cursor: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/users.conversations',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .query_param(new_parameter(token, key: 'token'))
                   .query_param(new_parameter(user, key: 'user'))
                   .query_param(new_parameter(types, key: 'types'))
                   .query_param(new_parameter(exclude_archived, key: 'exclude_archived'))
                   .query_param(new_parameter(limit, key: 'limit'))
                   .query_param(new_parameter(cursor, key: 'cursor'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(UsersConversationsSuccessSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 UsersConversationsErrorSchemaException))
        .execute
    end

    # Delete the user profile photo
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `users.profile:write`
    # @return [ApiResponse] Complete http response with raw body and status code.
    def users_delete_photo(token)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/users.deletePhoto',
                                     Server::DEFAULT)
                   .form_param(new_parameter(token, key: 'token')
                                .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(UsersDeletePhotoSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 UsersDeletePhotoErrorSchemaException))
        .execute
    end

    # Gets user presence information.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `users:read`
    # @param [String] user Optional parameter: User to get presence info on.
    # Defaults to the authed user.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def users_get_presence(token,
                           user: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/users.getPresence',
                                     Server::DEFAULT)
                   .query_param(new_parameter(token, key: 'token')
                                 .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .query_param(new_parameter(user, key: 'user'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ApiMethodUsersGetPresence.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 UsersCountsErrorSchemaException))
        .execute
    end

    # Get a user's identity.
    # @param [String] token Optional parameter: Authentication token. Requires
    # scope: `identity.basic`
    # @return [ApiResponse] Complete http response with raw body and status code.
    def users_identity(token: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/users.identity',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .query_param(new_parameter(token, key: 'token'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:dynamic_deserializer))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 UsersIdentityErrorSchemaException))
        .execute
    end

    # Gets information about a user.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `users:read`
    # @param [TrueClass | FalseClass] include_locale Optional parameter: Set
    # this to `true` to receive the locale for this user. Defaults to `false`
    # @param [String] user Optional parameter: User to get info on
    # @return [ApiResponse] Complete http response with raw body and status code.
    def users_info(token,
                   include_locale: nil,
                   user: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/users.info',
                                     Server::DEFAULT)
                   .query_param(new_parameter(token, key: 'token')
                                 .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .query_param(new_parameter(include_locale, key: 'include_locale'))
                   .query_param(new_parameter(user, key: 'user'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(UsersInfoSuccessSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 UsersInfoErrorSchemaException))
        .execute
    end

    # Lists all users in a Slack team.
    # @param [String] token Optional parameter: Authentication token. Requires
    # scope: `users:read`
    # @param [Integer] limit Optional parameter: The maximum number of items to
    # return. Fewer than the requested number of items may be returned, even if
    # the end of the users list hasn't been reached. Providing no `limit` value
    # will result in Slack attempting to deliver you the entire result set. If
    # the collection is too large you may experience `limit_required` or HTTP
    # 500 errors.
    # @param [String] cursor Optional parameter: Paginate through collections of
    # data by setting the `cursor` parameter to a `next_cursor` attribute
    # returned by a previous request's `response_metadata`. Default value
    # fetches the first "page" of the collection.
    # @param [TrueClass | FalseClass] include_locale Optional parameter: Set
    # this to `true` to receive the locale for users. Defaults to `false`
    # @return [ApiResponse] Complete http response with raw body and status code.
    def users_list(token: nil,
                   limit: nil,
                   cursor: nil,
                   include_locale: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/users.list',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .query_param(new_parameter(token, key: 'token'))
                   .query_param(new_parameter(limit, key: 'limit'))
                   .query_param(new_parameter(cursor, key: 'cursor'))
                   .query_param(new_parameter(include_locale, key: 'include_locale'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(UsersListSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 UsersListErrorSchemaException))
        .execute
    end

    # Find a user with an email address.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `users:read.email`
    # @param [String] email Required parameter: An email address belonging to a
    # user in the workspace
    # @return [ApiResponse] Complete http response with raw body and status code.
    def users_lookup_by_email(token,
                              email)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/users.lookupByEmail',
                                     Server::DEFAULT)
                   .query_param(new_parameter(token, key: 'token')
                                 .is_required(true))
                   .query_param(new_parameter(email, key: 'email')
                                 .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(UsersLookupByEmailSuccessSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 UsersLookupByEmailErrorSchemaException))
        .execute
    end

    # Marked a user as active. Deprecated and non-functional.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `users:write`
    # @return [ApiResponse] Complete http response with raw body and status code.
    def users_set_active(token)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/users.setActive',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'Content-Type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(UsersSetActiveSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 UsersSetActiveErrorSchemaException))
        .execute
    end

    # Set the user profile photo
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `users.profile:write`
    # @param [String] crop_w Optional parameter: Width/height of crop box
    # (always square)
    # @param [String] crop_x Optional parameter: X coordinate of top-left corner
    # of crop box
    # @param [String] crop_y Optional parameter: Y coordinate of top-left corner
    # of crop box
    # @param [String] image Optional parameter: File contents via
    # `multipart/form-data`.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def users_set_photo(token,
                        crop_w: nil,
                        crop_x: nil,
                        crop_y: nil,
                        image: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/users.setPhoto',
                                     Server::DEFAULT)
                   .form_param(new_parameter(token, key: 'token')
                                .is_required(true))
                   .form_param(new_parameter(crop_w, key: 'crop_w'))
                   .form_param(new_parameter(crop_x, key: 'crop_x'))
                   .form_param(new_parameter(crop_y, key: 'crop_y'))
                   .form_param(new_parameter(image, key: 'image'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(UsersSetPhotoSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 UsersSetPhotoErrorSchemaException))
        .execute
    end

    # Manually sets user presence.
    # @param [String] token Required parameter: Authentication token. Requires
    # scope: `users:write`
    # @param [String] presence Required parameter: Either `auto` or `away`
    # @return [ApiResponse] Complete http response with raw body and status code.
    def users_set_presence(token,
                           presence)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/users.setPresence',
                                     Server::DEFAULT)
                   .header_param(new_parameter(token, key: 'token')
                                  .is_required(true))
                   .form_param(new_parameter(presence, key: 'presence')
                                .is_required(true))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('slackAuth')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(UsersSetPresenceSchema.method(:from_hash))
                    .is_api_response(true)
                    .local_error('default',
                                 'Typical error response',
                                 UsersSetPresenceErrorSchemaException))
        .execute
    end
  end
end
