# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # Schema for successful response of admin.conversations.getTeams
  class AdminConversationsGetTeamsSchema < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_reader :ok

    # TODO: Write general description for this method
    # @return [ResponseMetadata]
    attr_accessor :response_metadata

    # TODO: Write general description for this method
    # @return [Array[String]]
    attr_accessor :team_ids

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['ok'] = 'ok'
      @_hash['response_metadata'] = 'response_metadata'
      @_hash['team_ids'] = 'team_ids'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        response_metadata
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(team_ids:, response_metadata: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @ok = 'True'
      @response_metadata = response_metadata unless response_metadata == SKIP
      @team_ids = team_ids
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      team_ids = hash.key?('team_ids') ? hash['team_ids'] : nil
      response_metadata = ResponseMetadata.from_hash(hash['response_metadata']) if
        hash['response_metadata']

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      AdminConversationsGetTeamsSchema.new(team_ids: team_ids,
                                           response_metadata: response_metadata,
                                           additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} ok: #{@ok}, response_metadata: #{@response_metadata}, team_ids:"\
      " #{@team_ids}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} ok: #{@ok.inspect}, response_metadata: #{@response_metadata.inspect},"\
      " team_ids: #{@team_ids.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
