# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # AdminConversationsSearchErrorEnum.
  class AdminConversationsSearchErrorEnum
    ADMIN_CONVERSATIONS_SEARCH_ERROR_ENUM = [
      # TODO: Write general description for FEATURE_NOT_ENABLED
      FEATURE_NOT_ENABLED = 'feature_not_enabled'.freeze,

      # TODO: Write general description for NOT_AN_ADMIN
      NOT_AN_ADMIN = 'not_an_admin'.freeze,

      # TODO: Write general description for NOT_AN_ENTERPRISE
      NOT_AN_ENTERPRISE = 'not_an_enterprise'.freeze,

      # TODO: Write general description for TEAM_NOT_FOUND
      TEAM_NOT_FOUND = 'team_not_found'.freeze,

      # TODO: Write general description for NOT_ALLOWED
      NOT_ALLOWED = 'not_allowed'.freeze,

      # TODO: Write general description for INVALID_AUTH
      INVALID_AUTH = 'invalid_auth'.freeze,

      # TODO: Write general description for INVALID_CURSOR
      INVALID_CURSOR = 'invalid_cursor'.freeze,

      # TODO: Write general description for INVALID_SEARCH_CHANNEL_TYPE
      INVALID_SEARCH_CHANNEL_TYPE = 'invalid_search_channel_type'.freeze,

      # TODO: Write general description for INVALID_SORT
      INVALID_SORT = 'invalid_sort'.freeze,

      # TODO: Write general description for INVALID_SORT_DIR
      INVALID_SORT_DIR = 'invalid_sort_dir'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      ADMIN_CONVERSATIONS_SEARCH_ERROR_ENUM.include?(value)
    end

    def self.from_value(value, default_value = FEATURE_NOT_ENABLED)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'feature_not_enabled' then FEATURE_NOT_ENABLED
      when 'not_an_admin' then NOT_AN_ADMIN
      when 'not_an_enterprise' then NOT_AN_ENTERPRISE
      when 'team_not_found' then TEAM_NOT_FOUND
      when 'not_allowed' then NOT_ALLOWED
      when 'invalid_auth' then INVALID_AUTH
      when 'invalid_cursor' then INVALID_CURSOR
      when 'invalid_search_channel_type' then INVALID_SEARCH_CHANNEL_TYPE
      when 'invalid_sort' then INVALID_SORT
      when 'invalid_sort_dir' then INVALID_SORT_DIR
      else
        default_value
      end
    end
  end
end
