# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # Generated from users.getPresence with shasum
  # e7251aec575d8863f9e0eb38663ae9dc26655f65
  class ApiMethodUsersGetPresence < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :auto_away

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :connection_count

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :last_activity

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :manual_away

    # TODO: Write general description for this method
    # @return [String]
    attr_reader :ok

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :online

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :presence

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['auto_away'] = 'auto_away'
      @_hash['connection_count'] = 'connection_count'
      @_hash['last_activity'] = 'last_activity'
      @_hash['manual_away'] = 'manual_away'
      @_hash['ok'] = 'ok'
      @_hash['online'] = 'online'
      @_hash['presence'] = 'presence'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        auto_away
        connection_count
        last_activity
        manual_away
        online
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(presence:, auto_away: SKIP, connection_count: SKIP,
                   last_activity: SKIP, manual_away: SKIP, online: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @auto_away = auto_away unless auto_away == SKIP
      @connection_count = connection_count unless connection_count == SKIP
      @last_activity = last_activity unless last_activity == SKIP
      @manual_away = manual_away unless manual_away == SKIP
      @ok = 'True'
      @online = online unless online == SKIP
      @presence = presence
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      presence = hash.key?('presence') ? hash['presence'] : nil
      auto_away = hash.key?('auto_away') ? hash['auto_away'] : SKIP
      connection_count =
        hash.key?('connection_count') ? hash['connection_count'] : SKIP
      last_activity = hash.key?('last_activity') ? hash['last_activity'] : SKIP
      manual_away = hash.key?('manual_away') ? hash['manual_away'] : SKIP
      online = hash.key?('online') ? hash['online'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ApiMethodUsersGetPresence.new(presence: presence,
                                    auto_away: auto_away,
                                    connection_count: connection_count,
                                    last_activity: last_activity,
                                    manual_away: manual_away,
                                    online: online,
                                    additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} auto_away: #{@auto_away}, connection_count: #{@connection_count},"\
      " last_activity: #{@last_activity}, manual_away: #{@manual_away}, ok: #{@ok}, online:"\
      " #{@online}, presence: #{@presence}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} auto_away: #{@auto_away.inspect}, connection_count:"\
      " #{@connection_count.inspect}, last_activity: #{@last_activity.inspect}, manual_away:"\
      " #{@manual_away.inspect}, ok: #{@ok.inspect}, online: #{@online.inspect}, presence:"\
      " #{@presence.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
