# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # Schema for successful response auth.test method
  class AuthTestSuccessSchema < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :bot_id

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :is_enterprise_install

    # TODO: Write general description for this method
    # @return [String]
    attr_reader :ok

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :team

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :team_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :url

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :user

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :user_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['bot_id'] = 'bot_id'
      @_hash['is_enterprise_install'] = 'is_enterprise_install'
      @_hash['ok'] = 'ok'
      @_hash['team'] = 'team'
      @_hash['team_id'] = 'team_id'
      @_hash['url'] = 'url'
      @_hash['user'] = 'user'
      @_hash['user_id'] = 'user_id'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        bot_id
        is_enterprise_install
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(team:, team_id:, url:, user:, user_id:, bot_id: SKIP,
                   is_enterprise_install: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @bot_id = bot_id unless bot_id == SKIP
      @is_enterprise_install = is_enterprise_install unless is_enterprise_install == SKIP
      @ok = 'True'
      @team = team
      @team_id = team_id
      @url = url
      @user = user
      @user_id = user_id
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      team = hash.key?('team') ? hash['team'] : nil
      team_id = hash.key?('team_id') ? hash['team_id'] : nil
      url = hash.key?('url') ? hash['url'] : nil
      user = hash.key?('user') ? hash['user'] : nil
      user_id = hash.key?('user_id') ? hash['user_id'] : nil
      bot_id = hash.key?('bot_id') ? hash['bot_id'] : SKIP
      is_enterprise_install =
        hash.key?('is_enterprise_install') ? hash['is_enterprise_install'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      AuthTestSuccessSchema.new(team: team,
                                team_id: team_id,
                                url: url,
                                user: user,
                                user_id: user_id,
                                bot_id: bot_id,
                                is_enterprise_install: is_enterprise_install,
                                additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} bot_id: #{@bot_id}, is_enterprise_install: #{@is_enterprise_install}, ok:"\
      " #{@ok}, team: #{@team}, team_id: #{@team_id}, url: #{@url}, user: #{@user}, user_id:"\
      " #{@user_id}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} bot_id: #{@bot_id.inspect}, is_enterprise_install:"\
      " #{@is_enterprise_install.inspect}, ok: #{@ok.inspect}, team: #{@team.inspect}, team_id:"\
      " #{@team_id.inspect}, url: #{@url.inspect}, user: #{@user.inspect}, user_id:"\
      " #{@user_id.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
