# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # BotProfileObject Model.
  class BotProfileObject < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :app_id

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :deleted

    # TODO: Write general description for this method
    # @return [Icons]
    attr_accessor :icons

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :team_id

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :updated

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['app_id'] = 'app_id'
      @_hash['deleted'] = 'deleted'
      @_hash['icons'] = 'icons'
      @_hash['id'] = 'id'
      @_hash['name'] = 'name'
      @_hash['team_id'] = 'team_id'
      @_hash['updated'] = 'updated'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(app_id:, deleted:, icons:, id:, name:, team_id:, updated:,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @app_id = app_id
      @deleted = deleted
      @icons = icons
      @id = id
      @name = name
      @team_id = team_id
      @updated = updated
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      app_id = hash.key?('app_id') ? hash['app_id'] : nil
      deleted = hash.key?('deleted') ? hash['deleted'] : nil
      icons = Icons.from_hash(hash['icons']) if hash['icons']
      id = hash.key?('id') ? hash['id'] : nil
      name = hash.key?('name') ? hash['name'] : nil
      team_id = hash.key?('team_id') ? hash['team_id'] : nil
      updated = hash.key?('updated') ? hash['updated'] : nil

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      BotProfileObject.new(app_id: app_id,
                           deleted: deleted,
                           icons: icons,
                           id: id,
                           name: name,
                           team_id: team_id,
                           updated: updated,
                           additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} app_id: #{@app_id}, deleted: #{@deleted}, icons: #{@icons}, id: #{@id},"\
      " name: #{@name}, team_id: #{@team_id}, updated: #{@updated}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} app_id: #{@app_id.inspect}, deleted: #{@deleted.inspect}, icons:"\
      " #{@icons.inspect}, id: #{@id.inspect}, name: #{@name.inspect}, team_id:"\
      " #{@team_id.inspect}, updated: #{@updated.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
