# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # Channel Model.
  class Channel < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [ResourcesInInfoFromAppsPermissionsInfo]
    attr_accessor :resources

    # TODO: Write general description for this method
    # @return [Array[String]]
    attr_accessor :scopes

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['resources'] = 'resources'
      @_hash['scopes'] = 'scopes'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        resources
        scopes
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(resources: SKIP, scopes: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @resources = resources unless resources == SKIP
      @scopes = scopes unless scopes == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      resources = ResourcesInInfoFromAppsPermissionsInfo.from_hash(hash['resources']) if
        hash['resources']
      scopes = hash.key?('scopes') ? hash['scopes'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Channel.new(resources: resources,
                  scopes: scopes,
                  additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} resources: #{@resources}, scopes: #{@scopes}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} resources: #{@resources.inspect}, scopes: #{@scopes.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
