# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # ChannelObject Model.
  class ChannelObject < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :accepted_user

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :created

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :creator

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :id

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :is_archived

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :is_channel

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :is_frozen

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :is_general

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :is_member

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :is_moved

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :is_mpim

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :is_non_threadable

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :is_org_shared

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :is_pending_ext_shared

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :is_private

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :is_read_only

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :is_shared

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :is_thread_only

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :last_read

    # TODO: Write general description for this method
    # @return [Object]
    attr_accessor :latest

    # TODO: Write general description for this method
    # @return [Array[String]]
    attr_accessor :members

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :name_normalized

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :num_members

    # TODO: Write general description for this method
    # @return [Array[String]]
    attr_accessor :pending_shared

    # TODO: Write general description for this method
    # @return [Array[String]]
    attr_accessor :previous_names

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :priority

    # TODO: Write general description for this method
    # @return [Purpose]
    attr_accessor :purpose

    # TODO: Write general description for this method
    # @return [Topic]
    attr_accessor :topic

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :unlinked

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :unread_count

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :unread_count_display

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['accepted_user'] = 'accepted_user'
      @_hash['created'] = 'created'
      @_hash['creator'] = 'creator'
      @_hash['id'] = 'id'
      @_hash['is_archived'] = 'is_archived'
      @_hash['is_channel'] = 'is_channel'
      @_hash['is_frozen'] = 'is_frozen'
      @_hash['is_general'] = 'is_general'
      @_hash['is_member'] = 'is_member'
      @_hash['is_moved'] = 'is_moved'
      @_hash['is_mpim'] = 'is_mpim'
      @_hash['is_non_threadable'] = 'is_non_threadable'
      @_hash['is_org_shared'] = 'is_org_shared'
      @_hash['is_pending_ext_shared'] = 'is_pending_ext_shared'
      @_hash['is_private'] = 'is_private'
      @_hash['is_read_only'] = 'is_read_only'
      @_hash['is_shared'] = 'is_shared'
      @_hash['is_thread_only'] = 'is_thread_only'
      @_hash['last_read'] = 'last_read'
      @_hash['latest'] = 'latest'
      @_hash['members'] = 'members'
      @_hash['name'] = 'name'
      @_hash['name_normalized'] = 'name_normalized'
      @_hash['num_members'] = 'num_members'
      @_hash['pending_shared'] = 'pending_shared'
      @_hash['previous_names'] = 'previous_names'
      @_hash['priority'] = 'priority'
      @_hash['purpose'] = 'purpose'
      @_hash['topic'] = 'topic'
      @_hash['unlinked'] = 'unlinked'
      @_hash['unread_count'] = 'unread_count'
      @_hash['unread_count_display'] = 'unread_count_display'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        accepted_user
        is_archived
        is_frozen
        is_general
        is_member
        is_moved
        is_non_threadable
        is_pending_ext_shared
        is_read_only
        is_thread_only
        last_read
        latest
        num_members
        pending_shared
        previous_names
        priority
        unlinked
        unread_count
        unread_count_display
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(created:, creator:, id:, is_channel:, is_mpim:,
                   is_org_shared:, is_private:, is_shared:, members:, name:,
                   name_normalized:, purpose:, topic:, accepted_user: SKIP,
                   is_archived: SKIP, is_frozen: SKIP, is_general: SKIP,
                   is_member: SKIP, is_moved: SKIP, is_non_threadable: SKIP,
                   is_pending_ext_shared: SKIP, is_read_only: SKIP,
                   is_thread_only: SKIP, last_read: SKIP, latest: SKIP,
                   num_members: SKIP, pending_shared: SKIP,
                   previous_names: SKIP, priority: SKIP, unlinked: SKIP,
                   unread_count: SKIP, unread_count_display: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @accepted_user = accepted_user unless accepted_user == SKIP
      @created = created
      @creator = creator
      @id = id
      @is_archived = is_archived unless is_archived == SKIP
      @is_channel = is_channel
      @is_frozen = is_frozen unless is_frozen == SKIP
      @is_general = is_general unless is_general == SKIP
      @is_member = is_member unless is_member == SKIP
      @is_moved = is_moved unless is_moved == SKIP
      @is_mpim = is_mpim
      @is_non_threadable = is_non_threadable unless is_non_threadable == SKIP
      @is_org_shared = is_org_shared
      @is_pending_ext_shared = is_pending_ext_shared unless is_pending_ext_shared == SKIP
      @is_private = is_private
      @is_read_only = is_read_only unless is_read_only == SKIP
      @is_shared = is_shared
      @is_thread_only = is_thread_only unless is_thread_only == SKIP
      @last_read = last_read unless last_read == SKIP
      @latest = latest unless latest == SKIP
      @members = members
      @name = name
      @name_normalized = name_normalized
      @num_members = num_members unless num_members == SKIP
      @pending_shared = pending_shared unless pending_shared == SKIP
      @previous_names = previous_names unless previous_names == SKIP
      @priority = priority unless priority == SKIP
      @purpose = purpose
      @topic = topic
      @unlinked = unlinked unless unlinked == SKIP
      @unread_count = unread_count unless unread_count == SKIP
      @unread_count_display = unread_count_display unless unread_count_display == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      created = hash.key?('created') ? hash['created'] : nil
      creator = hash.key?('creator') ? hash['creator'] : nil
      id = hash.key?('id') ? hash['id'] : nil
      is_channel = hash.key?('is_channel') ? hash['is_channel'] : nil
      is_mpim = hash.key?('is_mpim') ? hash['is_mpim'] : nil
      is_org_shared = hash.key?('is_org_shared') ? hash['is_org_shared'] : nil
      is_private = hash.key?('is_private') ? hash['is_private'] : nil
      is_shared = hash.key?('is_shared') ? hash['is_shared'] : nil
      members = hash.key?('members') ? hash['members'] : nil
      name = hash.key?('name') ? hash['name'] : nil
      name_normalized =
        hash.key?('name_normalized') ? hash['name_normalized'] : nil
      purpose = Purpose.from_hash(hash['purpose']) if hash['purpose']
      topic = Topic.from_hash(hash['topic']) if hash['topic']
      accepted_user = hash.key?('accepted_user') ? hash['accepted_user'] : SKIP
      is_archived = hash.key?('is_archived') ? hash['is_archived'] : SKIP
      is_frozen = hash.key?('is_frozen') ? hash['is_frozen'] : SKIP
      is_general = hash.key?('is_general') ? hash['is_general'] : SKIP
      is_member = hash.key?('is_member') ? hash['is_member'] : SKIP
      is_moved = hash.key?('is_moved') ? hash['is_moved'] : SKIP
      is_non_threadable =
        hash.key?('is_non_threadable') ? hash['is_non_threadable'] : SKIP
      is_pending_ext_shared =
        hash.key?('is_pending_ext_shared') ? hash['is_pending_ext_shared'] : SKIP
      is_read_only = hash.key?('is_read_only') ? hash['is_read_only'] : SKIP
      is_thread_only =
        hash.key?('is_thread_only') ? hash['is_thread_only'] : SKIP
      last_read = hash.key?('last_read') ? hash['last_read'] : SKIP
      latest = hash.key?('latest') ? hash['latest'] : SKIP
      num_members = hash.key?('num_members') ? hash['num_members'] : SKIP
      pending_shared =
        hash.key?('pending_shared') ? hash['pending_shared'] : SKIP
      previous_names =
        hash.key?('previous_names') ? hash['previous_names'] : SKIP
      priority = hash.key?('priority') ? hash['priority'] : SKIP
      unlinked = hash.key?('unlinked') ? hash['unlinked'] : SKIP
      unread_count = hash.key?('unread_count') ? hash['unread_count'] : SKIP
      unread_count_display =
        hash.key?('unread_count_display') ? hash['unread_count_display'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ChannelObject.new(created: created,
                        creator: creator,
                        id: id,
                        is_channel: is_channel,
                        is_mpim: is_mpim,
                        is_org_shared: is_org_shared,
                        is_private: is_private,
                        is_shared: is_shared,
                        members: members,
                        name: name,
                        name_normalized: name_normalized,
                        purpose: purpose,
                        topic: topic,
                        accepted_user: accepted_user,
                        is_archived: is_archived,
                        is_frozen: is_frozen,
                        is_general: is_general,
                        is_member: is_member,
                        is_moved: is_moved,
                        is_non_threadable: is_non_threadable,
                        is_pending_ext_shared: is_pending_ext_shared,
                        is_read_only: is_read_only,
                        is_thread_only: is_thread_only,
                        last_read: last_read,
                        latest: latest,
                        num_members: num_members,
                        pending_shared: pending_shared,
                        previous_names: previous_names,
                        priority: priority,
                        unlinked: unlinked,
                        unread_count: unread_count,
                        unread_count_display: unread_count_display,
                        additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} accepted_user: #{@accepted_user}, created: #{@created}, creator:"\
      " #{@creator}, id: #{@id}, is_archived: #{@is_archived}, is_channel: #{@is_channel},"\
      " is_frozen: #{@is_frozen}, is_general: #{@is_general}, is_member: #{@is_member}, is_moved:"\
      " #{@is_moved}, is_mpim: #{@is_mpim}, is_non_threadable: #{@is_non_threadable},"\
      " is_org_shared: #{@is_org_shared}, is_pending_ext_shared: #{@is_pending_ext_shared},"\
      " is_private: #{@is_private}, is_read_only: #{@is_read_only}, is_shared: #{@is_shared},"\
      " is_thread_only: #{@is_thread_only}, last_read: #{@last_read}, latest: #{@latest}, members:"\
      " #{@members}, name: #{@name}, name_normalized: #{@name_normalized}, num_members:"\
      " #{@num_members}, pending_shared: #{@pending_shared}, previous_names: #{@previous_names},"\
      " priority: #{@priority}, purpose: #{@purpose}, topic: #{@topic}, unlinked: #{@unlinked},"\
      " unread_count: #{@unread_count}, unread_count_display: #{@unread_count_display},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} accepted_user: #{@accepted_user.inspect}, created: #{@created.inspect},"\
      " creator: #{@creator.inspect}, id: #{@id.inspect}, is_archived: #{@is_archived.inspect},"\
      " is_channel: #{@is_channel.inspect}, is_frozen: #{@is_frozen.inspect}, is_general:"\
      " #{@is_general.inspect}, is_member: #{@is_member.inspect}, is_moved: #{@is_moved.inspect},"\
      " is_mpim: #{@is_mpim.inspect}, is_non_threadable: #{@is_non_threadable.inspect},"\
      " is_org_shared: #{@is_org_shared.inspect}, is_pending_ext_shared:"\
      " #{@is_pending_ext_shared.inspect}, is_private: #{@is_private.inspect}, is_read_only:"\
      " #{@is_read_only.inspect}, is_shared: #{@is_shared.inspect}, is_thread_only:"\
      " #{@is_thread_only.inspect}, last_read: #{@last_read.inspect}, latest: #{@latest.inspect},"\
      " members: #{@members.inspect}, name: #{@name.inspect}, name_normalized:"\
      " #{@name_normalized.inspect}, num_members: #{@num_members.inspect}, pending_shared:"\
      " #{@pending_shared.inspect}, previous_names: #{@previous_names.inspect}, priority:"\
      " #{@priority.inspect}, purpose: #{@purpose.inspect}, topic: #{@topic.inspect}, unlinked:"\
      " #{@unlinked.inspect}, unread_count: #{@unread_count.inspect}, unread_count_display:"\
      " #{@unread_count_display.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
