# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # Schema for successful response of chat.scheduleMessage method
  class ChatScheduleMessageSuccessSchema < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :channel

    # TODO: Write general description for this method
    # @return [Message]
    attr_accessor :message

    # TODO: Write general description for this method
    # @return [String]
    attr_reader :ok

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :post_at

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :scheduled_message_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['channel'] = 'channel'
      @_hash['message'] = 'message'
      @_hash['ok'] = 'ok'
      @_hash['post_at'] = 'post_at'
      @_hash['scheduled_message_id'] = 'scheduled_message_id'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(channel:, message:, post_at:, scheduled_message_id:,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @channel = channel
      @message = message
      @ok = 'True'
      @post_at = post_at
      @scheduled_message_id = scheduled_message_id
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      channel = hash.key?('channel') ? hash['channel'] : nil
      message = Message.from_hash(hash['message']) if hash['message']
      post_at = hash.key?('post_at') ? hash['post_at'] : nil
      scheduled_message_id =
        hash.key?('scheduled_message_id') ? hash['scheduled_message_id'] : nil

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ChatScheduleMessageSuccessSchema.new(channel: channel,
                                           message: message,
                                           post_at: post_at,
                                           scheduled_message_id: scheduled_message_id,
                                           additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} channel: #{@channel}, message: #{@message}, ok: #{@ok}, post_at:"\
      " #{@post_at}, scheduled_message_id: #{@scheduled_message_id}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} channel: #{@channel.inspect}, message: #{@message.inspect}, ok:"\
      " #{@ok.inspect}, post_at: #{@post_at.inspect}, scheduled_message_id:"\
      " #{@scheduled_message_id.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
