# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # Schema for successful response from chat.scheduledMessages.list method
  class ChatScheduledMessagesListSchema < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_reader :ok

    # TODO: Write general description for this method
    # @return [ResponseMetadata]
    attr_accessor :response_metadata

    # TODO: Write general description for this method
    # @return [Array[ScheduledMessage]]
    attr_accessor :scheduled_messages

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['ok'] = 'ok'
      @_hash['response_metadata'] = 'response_metadata'
      @_hash['scheduled_messages'] = 'scheduled_messages'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(response_metadata:, scheduled_messages:,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @ok = 'True'
      @response_metadata = response_metadata
      @scheduled_messages = scheduled_messages
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      response_metadata = ResponseMetadata.from_hash(hash['response_metadata']) if
        hash['response_metadata']
      # Parameter is an array, so we need to iterate through it
      scheduled_messages = nil
      unless hash['scheduled_messages'].nil?
        scheduled_messages = []
        hash['scheduled_messages'].each do |structure|
          scheduled_messages << (ScheduledMessage.from_hash(structure) if structure)
        end
      end

      scheduled_messages = nil unless hash.key?('scheduled_messages')

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ChatScheduledMessagesListSchema.new(response_metadata: response_metadata,
                                          scheduled_messages: scheduled_messages,
                                          additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} ok: #{@ok}, response_metadata: #{@response_metadata}, scheduled_messages:"\
      " #{@scheduled_messages}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} ok: #{@ok.inspect}, response_metadata: #{@response_metadata.inspect},"\
      " scheduled_messages: #{@scheduled_messages.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
