# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # Schema for successful response conversations.members method
  class ConversationsMembersSuccessSchema < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[String]]
    attr_accessor :members

    # TODO: Write general description for this method
    # @return [String]
    attr_reader :ok

    # TODO: Write general description for this method
    # @return [ResponseMetadata]
    attr_accessor :response_metadata

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['members'] = 'members'
      @_hash['ok'] = 'ok'
      @_hash['response_metadata'] = 'response_metadata'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(members:, response_metadata:, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @members = members
      @ok = 'True'
      @response_metadata = response_metadata
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      members = hash.key?('members') ? hash['members'] : nil
      response_metadata = ResponseMetadata.from_hash(hash['response_metadata']) if
        hash['response_metadata']

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ConversationsMembersSuccessSchema.new(members: members,
                                            response_metadata: response_metadata,
                                            additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} members: #{@members}, ok: #{@ok}, response_metadata: #{@response_metadata},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} members: #{@members.inspect}, ok: #{@ok.inspect}, response_metadata:"\
      " #{@response_metadata.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
