# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # Schema for successful response from conversations.replies method
  class ConversationsRepliesSuccessSchema < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :has_more

    # TODO: Write general description for this method
    # @return [Array[Object]]
    attr_accessor :messages

    # TODO: Write general description for this method
    # @return [String]
    attr_reader :ok

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['has_more'] = 'has_more'
      @_hash['messages'] = 'messages'
      @_hash['ok'] = 'ok'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        has_more
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(messages:, has_more: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @has_more = has_more unless has_more == SKIP
      @messages = messages
      @ok = 'True'
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      messages = hash.key?('messages') ? hash['messages'] : nil
      has_more = hash.key?('has_more') ? hash['has_more'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ConversationsRepliesSuccessSchema.new(messages: messages,
                                            has_more: has_more,
                                            additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} has_more: #{@has_more}, messages: #{@messages}, ok: #{@ok},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} has_more: #{@has_more.inspect}, messages: #{@messages.inspect}, ok:"\
      " #{@ok.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
