# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # Schema for successful response from conversations.leave method
  class ConversationsLeaveSuccessSchema < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :not_in_channel

    # TODO: Write general description for this method
    # @return [String]
    attr_reader :ok

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['not_in_channel'] = 'not_in_channel'
      @_hash['ok'] = 'ok'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        not_in_channel
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(not_in_channel: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @not_in_channel = not_in_channel unless not_in_channel == SKIP
      @ok = 'True'
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      not_in_channel =
        hash.key?('not_in_channel') ? hash['not_in_channel'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ConversationsLeaveSuccessSchema.new(not_in_channel: not_in_channel,
                                          additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} not_in_channel: #{@not_in_channel}, ok: #{@ok}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} not_in_channel: #{@not_in_channel.inspect}, ok: #{@ok.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
