# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # Schema for successful response from conversations.join method
  class ConversationsJoinSuccessSchema < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Object]
    attr_accessor :channel

    # TODO: Write general description for this method
    # @return [String]
    attr_reader :ok

    # TODO: Write general description for this method
    # @return [ResponseMetadata3]
    attr_accessor :response_metadata

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :warning

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['channel'] = 'channel'
      @_hash['ok'] = 'ok'
      @_hash['response_metadata'] = 'response_metadata'
      @_hash['warning'] = 'warning'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        response_metadata
        warning
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(channel:, response_metadata: SKIP, warning: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @channel = channel
      @ok = 'True'
      @response_metadata = response_metadata unless response_metadata == SKIP
      @warning = warning unless warning == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      channel = hash.key?('channel') ? hash['channel'] : nil
      response_metadata = ResponseMetadata3.from_hash(hash['response_metadata']) if
        hash['response_metadata']
      warning = hash.key?('warning') ? hash['warning'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ConversationsJoinSuccessSchema.new(channel: channel,
                                         response_metadata: response_metadata,
                                         warning: warning,
                                         additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} channel: #{@channel}, ok: #{@ok}, response_metadata: #{@response_metadata},"\
      " warning: #{@warning}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} channel: #{@channel.inspect}, ok: #{@ok.inspect}, response_metadata:"\
      " #{@response_metadata.inspect}, warning: #{@warning.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
