# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # Error10.
  class Error10
    ERROR10 = [
      # TODO: Write general description for FEATURE_NOT_ENABLED
      FEATURE_NOT_ENABLED = 'feature_not_enabled'.freeze,

      # TODO: Write general description for NOT_AN_ADMIN
      NOT_AN_ADMIN = 'not_an_admin'.freeze,

      # TODO: Write general description for CHANNEL_NOT_FOUND
      CHANNEL_NOT_FOUND = 'channel_not_found'.freeze,

      # TODO: Write general description for CHANNEL_TYPE_NOT_SUPPORTED
      CHANNEL_TYPE_NOT_SUPPORTED = 'channel_type_not_supported'.freeze,

      # TODO: Write general description for RESTRICTED_ACTION
      RESTRICTED_ACTION = 'restricted_action'.freeze,

      # TODO: Write general description for MISSING_SCOPE
      MISSING_SCOPE = 'missing_scope'.freeze,

      # TODO: Write general description for COULD_NOT_SET_CHANNEL_PREF
      COULD_NOT_SET_CHANNEL_PREF = 'could_not_set_channel_pref'.freeze,

      # TODO: Write general description for DEFAULT_ORG_WIDE_CHANNEL
      DEFAULT_ORG_WIDE_CHANNEL = 'default_org_wide_channel'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      ERROR10.include?(value)
    end

    def self.from_value(value, default_value = FEATURE_NOT_ENABLED)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'feature_not_enabled' then FEATURE_NOT_ENABLED
      when 'not_an_admin' then NOT_AN_ADMIN
      when 'channel_not_found' then CHANNEL_NOT_FOUND
      when 'channel_type_not_supported' then CHANNEL_TYPE_NOT_SUPPORTED
      when 'restricted_action' then RESTRICTED_ACTION
      when 'missing_scope' then MISSING_SCOPE
      when 'could_not_set_channel_pref' then COULD_NOT_SET_CHANNEL_PREF
      when 'default_org_wide_channel' then DEFAULT_ORG_WIDE_CHANNEL
      else
        default_value
      end
    end
  end
end
