# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # Error26.
  class Error26
    ERROR26 = [
      # TODO: Write general description for INVALID_TIME
      INVALID_TIME = 'invalid_time'.freeze,

      # TODO: Write general description for TIME_IN_PAST
      TIME_IN_PAST = 'time_in_past'.freeze,

      # TODO: Write general description for TIME_TOO_FAR
      TIME_TOO_FAR = 'time_too_far'.freeze,

      # TODO: Write general description for CHANNEL_NOT_FOUND
      CHANNEL_NOT_FOUND = 'channel_not_found'.freeze,

      # TODO: Write general description for NOT_IN_CHANNEL
      NOT_IN_CHANNEL = 'not_in_channel'.freeze,

      # TODO: Write general description for IS_ARCHIVED
      IS_ARCHIVED = 'is_archived'.freeze,

      # TODO: Write general description for MSG_TOO_LONG
      MSG_TOO_LONG = 'msg_too_long'.freeze,

      # TODO: Write general description for NO_TEXT
      NO_TEXT = 'no_text'.freeze,

      # TODO: Write general description for RESTRICTED_ACTION
      RESTRICTED_ACTION = 'restricted_action'.freeze,

      # TODO: Write general description for RESTRICTED_ACTION_READ_ONLY_CHANNEL
      RESTRICTED_ACTION_READ_ONLY_CHANNEL = 'restricted_action_read_only_channel'.freeze,

      # TODO: Write general description for
      # RESTRICTED_ACTION_THREAD_ONLY_CHANNEL
      RESTRICTED_ACTION_THREAD_ONLY_CHANNEL = 'restricted_action_thread_only_channel'.freeze,

      # TODO: Write general description for
      # RESTRICTED_ACTION_NON_THREADABLE_CHANNEL
      RESTRICTED_ACTION_NON_THREADABLE_CHANNEL = 'restricted_action_non_threadable_channel'.freeze,

      # TODO: Write general description for TOO_MANY_ATTACHMENTS
      TOO_MANY_ATTACHMENTS = 'too_many_attachments'.freeze,

      # TODO: Write general description for RATE_LIMITED
      RATE_LIMITED = 'rate_limited'.freeze,

      # TODO: Write general description for NOT_AUTHED
      NOT_AUTHED = 'not_authed'.freeze,

      # TODO: Write general description for INVALID_AUTH
      INVALID_AUTH = 'invalid_auth'.freeze,

      # TODO: Write general description for ACCOUNT_INACTIVE
      ACCOUNT_INACTIVE = 'account_inactive'.freeze,

      # TODO: Write general description for TOKEN_REVOKED
      TOKEN_REVOKED = 'token_revoked'.freeze,

      # TODO: Write general description for NO_PERMISSION
      NO_PERMISSION = 'no_permission'.freeze,

      # TODO: Write general description for ORG_LOGIN_REQUIRED
      ORG_LOGIN_REQUIRED = 'org_login_required'.freeze,

      # TODO: Write general description for EKM_ACCESS_DENIED
      EKM_ACCESS_DENIED = 'ekm_access_denied'.freeze,

      # TODO: Write general description for MISSING_SCOPE
      MISSING_SCOPE = 'missing_scope'.freeze,

      # TODO: Write general description for INVALID_ARGUMENTS
      INVALID_ARGUMENTS = 'invalid_arguments'.freeze,

      # TODO: Write general description for INVALID_ARG_NAME
      INVALID_ARG_NAME = 'invalid_arg_name'.freeze,

      # TODO: Write general description for INVALID_CHARSET
      INVALID_CHARSET = 'invalid_charset'.freeze,

      # TODO: Write general description for INVALID_FORM_DATA
      INVALID_FORM_DATA = 'invalid_form_data'.freeze,

      # TODO: Write general description for INVALID_POST_TYPE
      INVALID_POST_TYPE = 'invalid_post_type'.freeze,

      # TODO: Write general description for MISSING_POST_TYPE
      MISSING_POST_TYPE = 'missing_post_type'.freeze,

      # TODO: Write general description for TEAM_ADDED_TO_ORG
      TEAM_ADDED_TO_ORG = 'team_added_to_org'.freeze,

      # TODO: Write general description for INVALID_JSON
      INVALID_JSON = 'invalid_json'.freeze,

      # TODO: Write general description for JSON_NOT_OBJECT
      JSON_NOT_OBJECT = 'json_not_object'.freeze,

      # TODO: Write general description for REQUEST_TIMEOUT
      REQUEST_TIMEOUT = 'request_timeout'.freeze,

      # TODO: Write general description for UPGRADE_REQUIRED
      UPGRADE_REQUIRED = 'upgrade_required'.freeze,

      # TODO: Write general description for FATAL_ERROR
      FATAL_ERROR = 'fatal_error'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      ERROR26.include?(value)
    end

    def self.from_value(value, default_value = INVALID_TIME)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'invalid_time' then INVALID_TIME
      when 'time_in_past' then TIME_IN_PAST
      when 'time_too_far' then TIME_TOO_FAR
      when 'channel_not_found' then CHANNEL_NOT_FOUND
      when 'not_in_channel' then NOT_IN_CHANNEL
      when 'is_archived' then IS_ARCHIVED
      when 'msg_too_long' then MSG_TOO_LONG
      when 'no_text' then NO_TEXT
      when 'restricted_action' then RESTRICTED_ACTION
      when 'restricted_action_read_only_channel' then RESTRICTED_ACTION_READ_ONLY_CHANNEL
      when 'restricted_action_thread_only_channel' then RESTRICTED_ACTION_THREAD_ONLY_CHANNEL
      when 'restricted_action_non_threadable_channel' then RESTRICTED_ACTION_NON_THREADABLE_CHANNEL
      when 'too_many_attachments' then TOO_MANY_ATTACHMENTS
      when 'rate_limited' then RATE_LIMITED
      when 'not_authed' then NOT_AUTHED
      when 'invalid_auth' then INVALID_AUTH
      when 'account_inactive' then ACCOUNT_INACTIVE
      when 'token_revoked' then TOKEN_REVOKED
      when 'no_permission' then NO_PERMISSION
      when 'org_login_required' then ORG_LOGIN_REQUIRED
      when 'ekm_access_denied' then EKM_ACCESS_DENIED
      when 'missing_scope' then MISSING_SCOPE
      when 'invalid_arguments' then INVALID_ARGUMENTS
      when 'invalid_arg_name' then INVALID_ARG_NAME
      when 'invalid_charset' then INVALID_CHARSET
      when 'invalid_form_data' then INVALID_FORM_DATA
      when 'invalid_post_type' then INVALID_POST_TYPE
      when 'missing_post_type' then MISSING_POST_TYPE
      when 'team_added_to_org' then TEAM_ADDED_TO_ORG
      when 'invalid_json' then INVALID_JSON
      when 'json_not_object' then JSON_NOT_OBJECT
      when 'request_timeout' then REQUEST_TIMEOUT
      when 'upgrade_required' then UPGRADE_REQUIRED
      when 'fatal_error' then FATAL_ERROR
      else
        default_value
      end
    end
  end
end
