# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # ErrorsIsReturnedWhenAnErrorAssociatesAnUser Model.
  class ErrorsIsReturnedWhenAnErrorAssociatesAnUser < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Error35]
    attr_accessor :error

    # TODO: Write general description for this method
    # @return [String]
    attr_reader :ok

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :user

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['error'] = 'error'
      @_hash['ok'] = 'ok'
      @_hash['user'] = 'user'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        user
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(error:, user: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @error = error
      @ok = 'False'
      @user = user unless user == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      error = hash.key?('error') ? hash['error'] : nil
      user = hash.key?('user') ? hash['user'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ErrorsIsReturnedWhenAnErrorAssociatesAnUser.new(error: error,
                                                      user: user,
                                                      additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} error: #{@error}, ok: #{@ok}, user: #{@user}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} error: #{@error.inspect}, ok: #{@ok.inspect}, user: #{@user.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
