# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # Error1.
  class Error1
    ERROR1 = [
      # TODO: Write general description for FEATURE_NOT_ENABLED
      FEATURE_NOT_ENABLED = 'feature_not_enabled'.freeze,

      # TODO: Write general description for RESTRICTED_ACTION
      RESTRICTED_ACTION = 'restricted_action'.freeze,

      # TODO: Write general description for NAME_TAKEN
      NAME_TAKEN = 'name_taken'.freeze,

      # TODO: Write general description for CHANNEL_NOT_FOUND
      CHANNEL_NOT_FOUND = 'channel_not_found'.freeze,

      # TODO: Write general description for CHANNEL_TYPE_NOT_SUPPORTED
      CHANNEL_TYPE_NOT_SUPPORTED = 'channel_type_not_supported'.freeze,

      # TODO: Write general description for DEFAULT_ORG_WIDE_CHANNEL
      DEFAULT_ORG_WIDE_CHANNEL = 'default_org_wide_channel'.freeze,

      # TODO: Write general description for
      # METHOD_NOT_SUPPORTED_FOR_CHANNEL_TYPE
      METHOD_NOT_SUPPORTED_FOR_CHANNEL_TYPE = 'method_not_supported_for_channel_type'.freeze,

      # TODO: Write general description for COULD_NOT_CONVERT_CHANNEL
      COULD_NOT_CONVERT_CHANNEL = 'could_not_convert_channel'.freeze,

      # TODO: Write general description for EXTERNAL_CHANNEL_MIGRATING
      EXTERNAL_CHANNEL_MIGRATING = 'external_channel_migrating'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      ERROR1.include?(value)
    end

    def self.from_value(value, default_value = FEATURE_NOT_ENABLED)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'feature_not_enabled' then FEATURE_NOT_ENABLED
      when 'restricted_action' then RESTRICTED_ACTION
      when 'name_taken' then NAME_TAKEN
      when 'channel_not_found' then CHANNEL_NOT_FOUND
      when 'channel_type_not_supported' then CHANNEL_TYPE_NOT_SUPPORTED
      when 'default_org_wide_channel' then DEFAULT_ORG_WIDE_CHANNEL
      when 'method_not_supported_for_channel_type' then METHOD_NOT_SUPPORTED_FOR_CHANNEL_TYPE
      when 'could_not_convert_channel' then COULD_NOT_CONVERT_CHANNEL
      when 'external_channel_migrating' then EXTERNAL_CHANNEL_MIGRATING
      else
        default_value
      end
    end
  end
end
