# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # Error7.
  class Error7
    ERROR7 = [
      # TODO: Write general description for FEATURE_NOT_ENABLED
      FEATURE_NOT_ENABLED = 'feature_not_enabled'.freeze,

      # TODO: Write general description for CHANNEL_NOT_FOUND
      CHANNEL_NOT_FOUND = 'channel_not_found'.freeze,

      # TODO: Write general description for CHANNEL_TYPE_NOT_SUPPORTED
      CHANNEL_TYPE_NOT_SUPPORTED = 'channel_type_not_supported'.freeze,

      # TODO: Write general description for DEFAULT_ORG_WIDE_CHANNEL
      DEFAULT_ORG_WIDE_CHANNEL = 'default_org_wide_channel'.freeze,

      # TODO: Write general description for RESTRICTED_ACTION
      RESTRICTED_ACTION = 'restricted_action'.freeze,

      # TODO: Write general description for USER_MUST_BE_ADMIN
      USER_MUST_BE_ADMIN = 'user_must_be_admin'.freeze,

      # TODO: Write general description for FAILED_FOR_SOME_USERS
      FAILED_FOR_SOME_USERS = 'failed_for_some_users'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      ERROR7.include?(value)
    end

    def self.from_value(value, default_value = FEATURE_NOT_ENABLED)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'feature_not_enabled' then FEATURE_NOT_ENABLED
      when 'channel_not_found' then CHANNEL_NOT_FOUND
      when 'channel_type_not_supported' then CHANNEL_TYPE_NOT_SUPPORTED
      when 'default_org_wide_channel' then DEFAULT_ORG_WIDE_CHANNEL
      when 'restricted_action' then RESTRICTED_ACTION
      when 'user_must_be_admin' then USER_MUST_BE_ADMIN
      when 'failed_for_some_users' then FAILED_FOR_SOME_USERS
      else
        default_value
      end
    end
  end
end
