# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # Error33.
  class Error33
    ERROR33 = [
      # TODO: Write general description for MISSING_SCOPE
      MISSING_SCOPE = 'missing_scope'.freeze,

      # TODO: Write general description for CHANNEL_NOT_FOUND
      CHANNEL_NOT_FOUND = 'channel_not_found'.freeze,

      # TODO: Write general description for INVALID_TS_LATEST
      INVALID_TS_LATEST = 'invalid_ts_latest'.freeze,

      # TODO: Write general description for INVALID_TS_OLDEST
      INVALID_TS_OLDEST = 'invalid_ts_oldest'.freeze,

      # TODO: Write general description for NOT_AUTHED
      NOT_AUTHED = 'not_authed'.freeze,

      # TODO: Write general description for INVALID_AUTH
      INVALID_AUTH = 'invalid_auth'.freeze,

      # TODO: Write general description for ACCOUNT_INACTIVE
      ACCOUNT_INACTIVE = 'account_inactive'.freeze,

      # TODO: Write general description for INVALID_ARG_NAME
      INVALID_ARG_NAME = 'invalid_arg_name'.freeze,

      # TODO: Write general description for INVALID_ARRAY_ARG
      INVALID_ARRAY_ARG = 'invalid_array_arg'.freeze,

      # TODO: Write general description for INVALID_CHARSET
      INVALID_CHARSET = 'invalid_charset'.freeze,

      # TODO: Write general description for INVALID_FORM_DATA
      INVALID_FORM_DATA = 'invalid_form_data'.freeze,

      # TODO: Write general description for INVALID_POST_TYPE
      INVALID_POST_TYPE = 'invalid_post_type'.freeze,

      # TODO: Write general description for MISSING_POST_TYPE
      MISSING_POST_TYPE = 'missing_post_type'.freeze,

      # TODO: Write general description for INVALID_JSON
      INVALID_JSON = 'invalid_json'.freeze,

      # TODO: Write general description for JSON_NOT_OBJECT
      JSON_NOT_OBJECT = 'json_not_object'.freeze,

      # TODO: Write general description for REQUEST_TIMEOUT
      REQUEST_TIMEOUT = 'request_timeout'.freeze,

      # TODO: Write general description for UPGRADE_REQUIRED
      UPGRADE_REQUIRED = 'upgrade_required'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      ERROR33.include?(value)
    end

    def self.from_value(value, default_value = MISSING_SCOPE)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'missing_scope' then MISSING_SCOPE
      when 'channel_not_found' then CHANNEL_NOT_FOUND
      when 'invalid_ts_latest' then INVALID_TS_LATEST
      when 'invalid_ts_oldest' then INVALID_TS_OLDEST
      when 'not_authed' then NOT_AUTHED
      when 'invalid_auth' then INVALID_AUTH
      when 'account_inactive' then ACCOUNT_INACTIVE
      when 'invalid_arg_name' then INVALID_ARG_NAME
      when 'invalid_array_arg' then INVALID_ARRAY_ARG
      when 'invalid_charset' then INVALID_CHARSET
      when 'invalid_form_data' then INVALID_FORM_DATA
      when 'invalid_post_type' then INVALID_POST_TYPE
      when 'missing_post_type' then MISSING_POST_TYPE
      when 'invalid_json' then INVALID_JSON
      when 'json_not_object' then JSON_NOT_OBJECT
      when 'request_timeout' then REQUEST_TIMEOUT
      when 'upgrade_required' then UPGRADE_REQUIRED
      else
        default_value
      end
    end
  end
end
