# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # FilesUploadErrorEnum.
  class FilesUploadErrorEnum
    FILES_UPLOAD_ERROR_ENUM = [
      # TODO: Write general description for POSTING_TO_GENERAL_CHANNEL_DENIED
      POSTING_TO_GENERAL_CHANNEL_DENIED = 'posting_to_general_channel_denied'.freeze,

      # TODO: Write general description for INVALID_CHANNEL
      INVALID_CHANNEL = 'invalid_channel'.freeze,

      # TODO: Write general description for FILE_UPLOADS_DISABLED
      FILE_UPLOADS_DISABLED = 'file_uploads_disabled'.freeze,

      # TODO: Write general description for FILE_UPLOADS_EXCEPT_IMAGES_DISABLED
      FILE_UPLOADS_EXCEPT_IMAGES_DISABLED = 'file_uploads_except_images_disabled'.freeze,

      # TODO: Write general description for STORAGE_LIMIT_REACHED
      STORAGE_LIMIT_REACHED = 'storage_limit_reached'.freeze,

      # TODO: Write general description for NOT_AUTHED
      NOT_AUTHED = 'not_authed'.freeze,

      # TODO: Write general description for INVALID_AUTH
      INVALID_AUTH = 'invalid_auth'.freeze,

      # TODO: Write general description for ACCOUNT_INACTIVE
      ACCOUNT_INACTIVE = 'account_inactive'.freeze,

      # TODO: Write general description for NO_PERMISSION
      NO_PERMISSION = 'no_permission'.freeze,

      # TODO: Write general description for INVALID_ARG_NAME
      INVALID_ARG_NAME = 'invalid_arg_name'.freeze,

      # TODO: Write general description for INVALID_ARRAY_ARG
      INVALID_ARRAY_ARG = 'invalid_array_arg'.freeze,

      # TODO: Write general description for INVALID_CHARSET
      INVALID_CHARSET = 'invalid_charset'.freeze,

      # TODO: Write general description for INVALID_FORM_DATA
      INVALID_FORM_DATA = 'invalid_form_data'.freeze,

      # TODO: Write general description for INVALID_POST_TYPE
      INVALID_POST_TYPE = 'invalid_post_type'.freeze,

      # TODO: Write general description for MISSING_POST_TYPE
      MISSING_POST_TYPE = 'missing_post_type'.freeze,

      # TODO: Write general description for TEAM_ADDED_TO_ORG
      TEAM_ADDED_TO_ORG = 'team_added_to_org'.freeze,

      # TODO: Write general description for INVALID_JSON
      INVALID_JSON = 'invalid_json'.freeze,

      # TODO: Write general description for JSON_NOT_OBJECT
      JSON_NOT_OBJECT = 'json_not_object'.freeze,

      # TODO: Write general description for REQUEST_TIMEOUT
      REQUEST_TIMEOUT = 'request_timeout'.freeze,

      # TODO: Write general description for UPGRADE_REQUIRED
      UPGRADE_REQUIRED = 'upgrade_required'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      FILES_UPLOAD_ERROR_ENUM.include?(value)
    end

    def self.from_value(value, default_value = POSTING_TO_GENERAL_CHANNEL_DENIED)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'posting_to_general_channel_denied' then POSTING_TO_GENERAL_CHANNEL_DENIED
      when 'invalid_channel' then INVALID_CHANNEL
      when 'file_uploads_disabled' then FILE_UPLOADS_DISABLED
      when 'file_uploads_except_images_disabled' then FILE_UPLOADS_EXCEPT_IMAGES_DISABLED
      when 'storage_limit_reached' then STORAGE_LIMIT_REACHED
      when 'not_authed' then NOT_AUTHED
      when 'invalid_auth' then INVALID_AUTH
      when 'account_inactive' then ACCOUNT_INACTIVE
      when 'no_permission' then NO_PERMISSION
      when 'invalid_arg_name' then INVALID_ARG_NAME
      when 'invalid_array_arg' then INVALID_ARRAY_ARG
      when 'invalid_charset' then INVALID_CHARSET
      when 'invalid_form_data' then INVALID_FORM_DATA
      when 'invalid_post_type' then INVALID_POST_TYPE
      when 'missing_post_type' then MISSING_POST_TYPE
      when 'team_added_to_org' then TEAM_ADDED_TO_ORG
      when 'invalid_json' then INVALID_JSON
      when 'json_not_object' then JSON_NOT_OBJECT
      when 'request_timeout' then REQUEST_TIMEOUT
      when 'upgrade_required' then UPGRADE_REQUIRED
      else
        default_value
      end
    end
  end
end
