# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # Schema for successful response from files.info method
  class FilesInfoSchema < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[Object]]
    attr_accessor :comments

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :content_html

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :editor

    # TODO: Write general description for this method
    # @return [FileObject]
    attr_accessor :file

    # TODO: Write general description for this method
    # @return [String]
    attr_reader :ok

    # TODO: Write general description for this method
    # @return [PagingObject]
    attr_accessor :paging

    # TODO: Write general description for this method
    # @return [Object]
    attr_accessor :response_metadata

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['comments'] = 'comments'
      @_hash['content_html'] = 'content_html'
      @_hash['editor'] = 'editor'
      @_hash['file'] = 'file'
      @_hash['ok'] = 'ok'
      @_hash['paging'] = 'paging'
      @_hash['response_metadata'] = 'response_metadata'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        content_html
        editor
        paging
        response_metadata
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        content_html
      ]
    end

    def initialize(comments:, file:, content_html: SKIP, editor: SKIP,
                   paging: SKIP, response_metadata: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @comments = comments
      @content_html = content_html unless content_html == SKIP
      @editor = editor unless editor == SKIP
      @file = file
      @ok = 'True'
      @paging = paging unless paging == SKIP
      @response_metadata = response_metadata unless response_metadata == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      comments = hash.key?('comments') ? hash['comments'] : nil
      file = FileObject.from_hash(hash['file']) if hash['file']
      content_html = hash.key?('content_html') ? hash['content_html'] : SKIP
      editor = hash.key?('editor') ? hash['editor'] : SKIP
      paging = PagingObject.from_hash(hash['paging']) if hash['paging']
      response_metadata =
        hash.key?('response_metadata') ? hash['response_metadata'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      FilesInfoSchema.new(comments: comments,
                          file: file,
                          content_html: content_html,
                          editor: editor,
                          paging: paging,
                          response_metadata: response_metadata,
                          additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} comments: #{@comments}, content_html: #{@content_html}, editor: #{@editor},"\
      " file: #{@file}, ok: #{@ok}, paging: #{@paging}, response_metadata: #{@response_metadata},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} comments: #{@comments.inspect}, content_html: #{@content_html.inspect},"\
      " editor: #{@editor.inspect}, file: #{@file.inspect}, ok: #{@ok.inspect}, paging:"\
      " #{@paging.inspect}, response_metadata: #{@response_metadata.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
