# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # FileCommentObject Model.
  class FileCommentObject < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :comment

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :created

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :id

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :is_intro

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :is_starred

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :num_stars

    # TODO: Write general description for this method
    # @return [Object]
    attr_accessor :pinned_info

    # TODO: Write general description for this method
    # @return [Array[String]]
    attr_accessor :pinned_to

    # TODO: Write general description for this method
    # @return [Array[ReactionObject]]
    attr_accessor :reactions

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :timestamp

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :user

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['comment'] = 'comment'
      @_hash['created'] = 'created'
      @_hash['id'] = 'id'
      @_hash['is_intro'] = 'is_intro'
      @_hash['is_starred'] = 'is_starred'
      @_hash['num_stars'] = 'num_stars'
      @_hash['pinned_info'] = 'pinned_info'
      @_hash['pinned_to'] = 'pinned_to'
      @_hash['reactions'] = 'reactions'
      @_hash['timestamp'] = 'timestamp'
      @_hash['user'] = 'user'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        is_starred
        num_stars
        pinned_info
        pinned_to
        reactions
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(comment:, created:, id:, is_intro:, timestamp:, user:,
                   is_starred: SKIP, num_stars: SKIP, pinned_info: SKIP,
                   pinned_to: SKIP, reactions: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @comment = comment
      @created = created
      @id = id
      @is_intro = is_intro
      @is_starred = is_starred unless is_starred == SKIP
      @num_stars = num_stars unless num_stars == SKIP
      @pinned_info = pinned_info unless pinned_info == SKIP
      @pinned_to = pinned_to unless pinned_to == SKIP
      @reactions = reactions unless reactions == SKIP
      @timestamp = timestamp
      @user = user
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      comment = hash.key?('comment') ? hash['comment'] : nil
      created = hash.key?('created') ? hash['created'] : nil
      id = hash.key?('id') ? hash['id'] : nil
      is_intro = hash.key?('is_intro') ? hash['is_intro'] : nil
      timestamp = hash.key?('timestamp') ? hash['timestamp'] : nil
      user = hash.key?('user') ? hash['user'] : nil
      is_starred = hash.key?('is_starred') ? hash['is_starred'] : SKIP
      num_stars = hash.key?('num_stars') ? hash['num_stars'] : SKIP
      pinned_info = hash.key?('pinned_info') ? hash['pinned_info'] : SKIP
      pinned_to = hash.key?('pinned_to') ? hash['pinned_to'] : SKIP
      # Parameter is an array, so we need to iterate through it
      reactions = nil
      unless hash['reactions'].nil?
        reactions = []
        hash['reactions'].each do |structure|
          reactions << (ReactionObject.from_hash(structure) if structure)
        end
      end

      reactions = SKIP unless hash.key?('reactions')

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      FileCommentObject.new(comment: comment,
                            created: created,
                            id: id,
                            is_intro: is_intro,
                            timestamp: timestamp,
                            user: user,
                            is_starred: is_starred,
                            num_stars: num_stars,
                            pinned_info: pinned_info,
                            pinned_to: pinned_to,
                            reactions: reactions,
                            additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} comment: #{@comment}, created: #{@created}, id: #{@id}, is_intro:"\
      " #{@is_intro}, is_starred: #{@is_starred}, num_stars: #{@num_stars}, pinned_info:"\
      " #{@pinned_info}, pinned_to: #{@pinned_to}, reactions: #{@reactions}, timestamp:"\
      " #{@timestamp}, user: #{@user}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} comment: #{@comment.inspect}, created: #{@created.inspect}, id:"\
      " #{@id.inspect}, is_intro: #{@is_intro.inspect}, is_starred: #{@is_starred.inspect},"\
      " num_stars: #{@num_stars.inspect}, pinned_info: #{@pinned_info.inspect}, pinned_to:"\
      " #{@pinned_to.inspect}, reactions: #{@reactions.inspect}, timestamp: #{@timestamp.inspect},"\
      " user: #{@user.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
