# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # Icons1 Model.
  class Icons1 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :emoji

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :image_64

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['emoji'] = 'emoji'
      @_hash['image_64'] = 'image_64'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        emoji
        image_64
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(emoji: SKIP, image_64: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @emoji = emoji unless emoji == SKIP
      @image_64 = image_64 unless image_64 == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      emoji = hash.key?('emoji') ? hash['emoji'] : SKIP
      image_64 = hash.key?('image_64') ? hash['image_64'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Icons1.new(emoji: emoji,
                 image_64: image_64,
                 additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} emoji: #{@emoji}, image_64: #{@image_64}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} emoji: #{@emoji.inspect}, image_64: #{@image_64.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
