# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # Icons Model.
  class Icons < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :image_36

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :image_48

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :image_72

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['image_36'] = 'image_36'
      @_hash['image_48'] = 'image_48'
      @_hash['image_72'] = 'image_72'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(image_36:, image_48:, image_72:, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @image_36 = image_36
      @image_48 = image_48
      @image_72 = image_72
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      image_36 = hash.key?('image_36') ? hash['image_36'] : nil
      image_48 = hash.key?('image_48') ? hash['image_48'] : nil
      image_72 = hash.key?('image_72') ? hash['image_72'] : nil

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Icons.new(image_36: image_36,
                image_48: image_48,
                image_72: image_72,
                additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} image_36: #{@image_36}, image_48: #{@image_48}, image_72: #{@image_72},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} image_36: #{@image_36.inspect}, image_48: #{@image_48.inspect}, image_72:"\
      " #{@image_72.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
