# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # Message Model.
  class Message < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :bot_id

    # TODO: Write general description for this method
    # @return [BotProfileObject]
    attr_accessor :bot_profile

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :team

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :text

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :type

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :user

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :username

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['bot_id'] = 'bot_id'
      @_hash['bot_profile'] = 'bot_profile'
      @_hash['team'] = 'team'
      @_hash['text'] = 'text'
      @_hash['type'] = 'type'
      @_hash['user'] = 'user'
      @_hash['username'] = 'username'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        bot_profile
        username
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(bot_id:, team:, text:, type:, user:, bot_profile: SKIP,
                   username: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @bot_id = bot_id
      @bot_profile = bot_profile unless bot_profile == SKIP
      @team = team
      @text = text
      @type = type
      @user = user
      @username = username unless username == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      bot_id = hash.key?('bot_id') ? hash['bot_id'] : nil
      team = hash.key?('team') ? hash['team'] : nil
      text = hash.key?('text') ? hash['text'] : nil
      type = hash.key?('type') ? hash['type'] : nil
      user = hash.key?('user') ? hash['user'] : nil
      bot_profile = BotProfileObject.from_hash(hash['bot_profile']) if hash['bot_profile']
      username = hash.key?('username') ? hash['username'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Message.new(bot_id: bot_id,
                  team: team,
                  text: text,
                  type: type,
                  user: user,
                  bot_profile: bot_profile,
                  username: username,
                  additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} bot_id: #{@bot_id}, bot_profile: #{@bot_profile}, team: #{@team}, text:"\
      " #{@text}, type: #{@type}, user: #{@user}, username: #{@username}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} bot_id: #{@bot_id.inspect}, bot_profile: #{@bot_profile.inspect}, team:"\
      " #{@team.inspect}, text: #{@text.inspect}, type: #{@type.inspect}, user: #{@user.inspect},"\
      " username: #{@username.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
