# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # MessageObject1 Model.
  class MessageObject1 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[Object]]
    attr_accessor :attachments

    # TODO: Write general description for this method
    # @return [Object]
    attr_accessor :blocks

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :text

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['attachments'] = 'attachments'
      @_hash['blocks'] = 'blocks'
      @_hash['text'] = 'text'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        attachments
        blocks
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(text:, attachments: SKIP, blocks: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @attachments = attachments unless attachments == SKIP
      @blocks = blocks unless blocks == SKIP
      @text = text
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      text = hash.key?('text') ? hash['text'] : nil
      attachments = hash.key?('attachments') ? hash['attachments'] : SKIP
      blocks = hash.key?('blocks') ? hash['blocks'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      MessageObject1.new(text: text,
                         attachments: attachments,
                         blocks: blocks,
                         additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} attachments: #{@attachments}, blocks: #{@blocks}, text: #{@text},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} attachments: #{@attachments.inspect}, blocks: #{@blocks.inspect}, text:"\
      " #{@text.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
