# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # Schema for successful response from migration.exchange method
  class MigrationExchangeSuccessSchema < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :enterprise_id

    # TODO: Write general description for this method
    # @return [Array[String]]
    attr_accessor :invalid_user_ids

    # TODO: Write general description for this method
    # @return [String]
    attr_reader :ok

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :team_id

    # TODO: Write general description for this method
    # @return [Object]
    attr_accessor :user_id_map

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['enterprise_id'] = 'enterprise_id'
      @_hash['invalid_user_ids'] = 'invalid_user_ids'
      @_hash['ok'] = 'ok'
      @_hash['team_id'] = 'team_id'
      @_hash['user_id_map'] = 'user_id_map'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        invalid_user_ids
        user_id_map
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(enterprise_id:, team_id:, invalid_user_ids: SKIP,
                   user_id_map: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @enterprise_id = enterprise_id
      @invalid_user_ids = invalid_user_ids unless invalid_user_ids == SKIP
      @ok = 'True'
      @team_id = team_id
      @user_id_map = user_id_map unless user_id_map == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      enterprise_id = hash.key?('enterprise_id') ? hash['enterprise_id'] : nil
      team_id = hash.key?('team_id') ? hash['team_id'] : nil
      invalid_user_ids =
        hash.key?('invalid_user_ids') ? hash['invalid_user_ids'] : SKIP
      user_id_map = hash.key?('user_id_map') ? hash['user_id_map'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      MigrationExchangeSuccessSchema.new(enterprise_id: enterprise_id,
                                         team_id: team_id,
                                         invalid_user_ids: invalid_user_ids,
                                         user_id_map: user_id_map,
                                         additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} enterprise_id: #{@enterprise_id}, invalid_user_ids: #{@invalid_user_ids},"\
      " ok: #{@ok}, team_id: #{@team_id}, user_id_map: #{@user_id_map}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} enterprise_id: #{@enterprise_id.inspect}, invalid_user_ids:"\
      " #{@invalid_user_ids.inspect}, ok: #{@ok.inspect}, team_id: #{@team_id.inspect},"\
      " user_id_map: #{@user_id_map.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
