# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # ObjsTeamProfileField Model.
  class ObjsTeamProfileField < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :field_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :hint

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :id

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :is_hidden

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :label

    # TODO: Write general description for this method
    # @return [Object]
    attr_accessor :options

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :ordering

    # TODO: Write general description for this method
    # @return [Array[String]]
    attr_accessor :possible_values

    # TODO: Write general description for this method
    # @return [Type]
    attr_accessor :type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['field_name'] = 'field_name'
      @_hash['hint'] = 'hint'
      @_hash['id'] = 'id'
      @_hash['is_hidden'] = 'is_hidden'
      @_hash['label'] = 'label'
      @_hash['options'] = 'options'
      @_hash['ordering'] = 'ordering'
      @_hash['possible_values'] = 'possible_values'
      @_hash['type'] = 'type'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        field_name
        is_hidden
        options
        possible_values
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        field_name
        possible_values
      ]
    end

    def initialize(hint:, id:, label:, ordering:, type:, field_name: SKIP,
                   is_hidden: SKIP, options: SKIP, possible_values: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @field_name = field_name unless field_name == SKIP
      @hint = hint
      @id = id
      @is_hidden = is_hidden unless is_hidden == SKIP
      @label = label
      @options = options unless options == SKIP
      @ordering = ordering
      @possible_values = possible_values unless possible_values == SKIP
      @type = type
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      hint = hash.key?('hint') ? hash['hint'] : nil
      id = hash.key?('id') ? hash['id'] : nil
      label = hash.key?('label') ? hash['label'] : nil
      ordering = hash.key?('ordering') ? hash['ordering'] : nil
      type = hash.key?('type') ? hash['type'] : nil
      field_name = hash.key?('field_name') ? hash['field_name'] : SKIP
      is_hidden = hash.key?('is_hidden') ? hash['is_hidden'] : SKIP
      options = hash.key?('options') ? hash['options'] : SKIP
      possible_values =
        hash.key?('possible_values') ? hash['possible_values'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ObjsTeamProfileField.new(hint: hint,
                               id: id,
                               label: label,
                               ordering: ordering,
                               type: type,
                               field_name: field_name,
                               is_hidden: is_hidden,
                               options: options,
                               possible_values: possible_values,
                               additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} field_name: #{@field_name}, hint: #{@hint}, id: #{@id}, is_hidden:"\
      " #{@is_hidden}, label: #{@label}, options: #{@options}, ordering: #{@ordering},"\
      " possible_values: #{@possible_values}, type: #{@type}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} field_name: #{@field_name.inspect}, hint: #{@hint.inspect}, id:"\
      " #{@id.inspect}, is_hidden: #{@is_hidden.inspect}, label: #{@label.inspect}, options:"\
      " #{@options.inspect}, ordering: #{@ordering.inspect}, possible_values:"\
      " #{@possible_values.inspect}, type: #{@type.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
