# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # ObjsIcon Model.
  class ObjsIcon < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :image_102

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :image_132

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :image_230

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :image_34

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :image_44

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :image_68

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :image_88

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :image_default

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['image_102'] = 'image_102'
      @_hash['image_132'] = 'image_132'
      @_hash['image_230'] = 'image_230'
      @_hash['image_34'] = 'image_34'
      @_hash['image_44'] = 'image_44'
      @_hash['image_68'] = 'image_68'
      @_hash['image_88'] = 'image_88'
      @_hash['image_default'] = 'image_default'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        image_102
        image_132
        image_230
        image_34
        image_44
        image_68
        image_88
        image_default
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(image_102: SKIP, image_132: SKIP, image_230: SKIP,
                   image_34: SKIP, image_44: SKIP, image_68: SKIP,
                   image_88: SKIP, image_default: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @image_102 = image_102 unless image_102 == SKIP
      @image_132 = image_132 unless image_132 == SKIP
      @image_230 = image_230 unless image_230 == SKIP
      @image_34 = image_34 unless image_34 == SKIP
      @image_44 = image_44 unless image_44 == SKIP
      @image_68 = image_68 unless image_68 == SKIP
      @image_88 = image_88 unless image_88 == SKIP
      @image_default = image_default unless image_default == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      image_102 = hash.key?('image_102') ? hash['image_102'] : SKIP
      image_132 = hash.key?('image_132') ? hash['image_132'] : SKIP
      image_230 = hash.key?('image_230') ? hash['image_230'] : SKIP
      image_34 = hash.key?('image_34') ? hash['image_34'] : SKIP
      image_44 = hash.key?('image_44') ? hash['image_44'] : SKIP
      image_68 = hash.key?('image_68') ? hash['image_68'] : SKIP
      image_88 = hash.key?('image_88') ? hash['image_88'] : SKIP
      image_default = hash.key?('image_default') ? hash['image_default'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ObjsIcon.new(image_102: image_102,
                   image_132: image_132,
                   image_230: image_230,
                   image_34: image_34,
                   image_44: image_44,
                   image_68: image_68,
                   image_88: image_88,
                   image_default: image_default,
                   additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} image_102: #{@image_102}, image_132: #{@image_132}, image_230:"\
      " #{@image_230}, image_34: #{@image_34}, image_44: #{@image_44}, image_68: #{@image_68},"\
      " image_88: #{@image_88}, image_default: #{@image_default}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} image_102: #{@image_102.inspect}, image_132: #{@image_132.inspect},"\
      " image_230: #{@image_230.inspect}, image_34: #{@image_34.inspect}, image_44:"\
      " #{@image_44.inspect}, image_68: #{@image_68.inspect}, image_88: #{@image_88.inspect},"\
      " image_default: #{@image_default.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
