# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # PagingObject Model.
  class PagingObject < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :count

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :page

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :pages

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :per_page

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :spill

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :total

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['count'] = 'count'
      @_hash['page'] = 'page'
      @_hash['pages'] = 'pages'
      @_hash['per_page'] = 'per_page'
      @_hash['spill'] = 'spill'
      @_hash['total'] = 'total'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        count
        pages
        per_page
        spill
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(page:, total:, count: SKIP, pages: SKIP, per_page: SKIP,
                   spill: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @count = count unless count == SKIP
      @page = page
      @pages = pages unless pages == SKIP
      @per_page = per_page unless per_page == SKIP
      @spill = spill unless spill == SKIP
      @total = total
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      page = hash.key?('page') ? hash['page'] : nil
      total = hash.key?('total') ? hash['total'] : nil
      count = hash.key?('count') ? hash['count'] : SKIP
      pages = hash.key?('pages') ? hash['pages'] : SKIP
      per_page = hash.key?('per_page') ? hash['per_page'] : SKIP
      spill = hash.key?('spill') ? hash['spill'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      PagingObject.new(page: page,
                       total: total,
                       count: count,
                       pages: pages,
                       per_page: per_page,
                       spill: spill,
                       additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} count: #{@count}, page: #{@page}, pages: #{@pages}, per_page: #{@per_page},"\
      " spill: #{@spill}, total: #{@total}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} count: #{@count.inspect}, page: #{@page.inspect}, pages: #{@pages.inspect},"\
      " per_page: #{@per_page.inspect}, spill: #{@spill.inspect}, total: #{@total.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
