# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # PinsRemoveErrorEnum.
  class PinsRemoveErrorEnum
    PINS_REMOVE_ERROR_ENUM = [
      # TODO: Write general description for BAD_TIMESTAMP
      BAD_TIMESTAMP = 'bad_timestamp'.freeze,

      # TODO: Write general description for FILE_NOT_FOUND
      FILE_NOT_FOUND = 'file_not_found'.freeze,

      # TODO: Write general description for FILE_COMMENT_NOT_FOUND
      FILE_COMMENT_NOT_FOUND = 'file_comment_not_found'.freeze,

      # TODO: Write general description for MESSAGE_NOT_FOUND
      MESSAGE_NOT_FOUND = 'message_not_found'.freeze,

      # TODO: Write general description for NO_ITEM_SPECIFIED
      NO_ITEM_SPECIFIED = 'no_item_specified'.freeze,

      # TODO: Write general description for NOT_PINNED
      NOT_PINNED = 'not_pinned'.freeze,

      # TODO: Write general description for PERMISSION_DENIED
      PERMISSION_DENIED = 'permission_denied'.freeze,

      # TODO: Write general description for NOT_AUTHED
      NOT_AUTHED = 'not_authed'.freeze,

      # TODO: Write general description for INVALID_AUTH
      INVALID_AUTH = 'invalid_auth'.freeze,

      # TODO: Write general description for ACCOUNT_INACTIVE
      ACCOUNT_INACTIVE = 'account_inactive'.freeze,

      # TODO: Write general description for NO_PERMISSION
      NO_PERMISSION = 'no_permission'.freeze,

      # TODO: Write general description for INVALID_ARG_NAME
      INVALID_ARG_NAME = 'invalid_arg_name'.freeze,

      # TODO: Write general description for INVALID_ARRAY_ARG
      INVALID_ARRAY_ARG = 'invalid_array_arg'.freeze,

      # TODO: Write general description for INVALID_CHARSET
      INVALID_CHARSET = 'invalid_charset'.freeze,

      # TODO: Write general description for INVALID_FORM_DATA
      INVALID_FORM_DATA = 'invalid_form_data'.freeze,

      # TODO: Write general description for INVALID_POST_TYP
      INVALID_POST_TYP = 'invalid_post_typ'.freeze,

      # TODO: Write general description for MISSING_POST_TYP
      MISSING_POST_TYP = 'missing_post_typ'.freeze,

      # TODO: Write general description for TEAM_ADDED_TO_ORG
      TEAM_ADDED_TO_ORG = 'team_added_to_org'.freeze,

      # TODO: Write general description for INVALID_JSON
      INVALID_JSON = 'invalid_json'.freeze,

      # TODO: Write general description for JSON_NOT_OBJECT
      JSON_NOT_OBJECT = 'json_not_object'.freeze,

      # TODO: Write general description for REQUEST_TIMEOU
      REQUEST_TIMEOU = 'request_timeou'.freeze,

      # TODO: Write general description for UPGRADE_REQUIRED
      UPGRADE_REQUIRED = 'upgrade_required'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      PINS_REMOVE_ERROR_ENUM.include?(value)
    end

    def self.from_value(value, default_value = BAD_TIMESTAMP)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'bad_timestamp' then BAD_TIMESTAMP
      when 'file_not_found' then FILE_NOT_FOUND
      when 'file_comment_not_found' then FILE_COMMENT_NOT_FOUND
      when 'message_not_found' then MESSAGE_NOT_FOUND
      when 'no_item_specified' then NO_ITEM_SPECIFIED
      when 'not_pinned' then NOT_PINNED
      when 'permission_denied' then PERMISSION_DENIED
      when 'not_authed' then NOT_AUTHED
      when 'invalid_auth' then INVALID_AUTH
      when 'account_inactive' then ACCOUNT_INACTIVE
      when 'no_permission' then NO_PERMISSION
      when 'invalid_arg_name' then INVALID_ARG_NAME
      when 'invalid_array_arg' then INVALID_ARRAY_ARG
      when 'invalid_charset' then INVALID_CHARSET
      when 'invalid_form_data' then INVALID_FORM_DATA
      when 'invalid_post_typ' then INVALID_POST_TYP
      when 'missing_post_typ' then MISSING_POST_TYP
      when 'team_added_to_org' then TEAM_ADDED_TO_ORG
      when 'invalid_json' then INVALID_JSON
      when 'json_not_object' then JSON_NOT_OBJECT
      when 'request_timeou' then REQUEST_TIMEOU
      when 'upgrade_required' then UPGRADE_REQUIRED
      else
        default_value
      end
    end
  end
end
