# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # Plan.
  class Plan
    PLAN = [
      # TODO: Write general description for STD
      STD = 'std'.freeze,

      # TODO: Write general description for PLUS
      PLUS = 'plus'.freeze,

      # TODO: Write general description for COMPLIANCE
      COMPLIANCE = 'compliance'.freeze,

      # TODO: Write general description for ENTERPRISE
      ENTERPRISE = 'enterprise'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      PLAN.include?(value)
    end

    def self.from_value(value, default_value = STD)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'std' then STD
      when 'plus' then PLUS
      when 'compliance' then COMPLIANCE
      when 'enterprise' then ENTERPRISE
      else
        default_value
      end
    end
  end
end
