# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # Prefs1 Model.
  class Prefs1 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [CanThread]
    attr_accessor :can_thread

    # TODO: Write general description for this method
    # @return [WhoCanPost]
    attr_accessor :who_can_post

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['can_thread'] = 'can_thread'
      @_hash['who_can_post'] = 'who_can_post'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        can_thread
        who_can_post
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(can_thread: SKIP, who_can_post: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @can_thread = can_thread unless can_thread == SKIP
      @who_can_post = who_can_post unless who_can_post == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      can_thread = CanThread.from_hash(hash['can_thread']) if hash['can_thread']
      who_can_post = WhoCanPost.from_hash(hash['who_can_post']) if hash['who_can_post']

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Prefs1.new(can_thread: can_thread,
                 who_can_post: who_can_post,
                 additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} can_thread: #{@can_thread}, who_can_post: #{@who_can_post},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} can_thread: #{@can_thread.inspect}, who_can_post: #{@who_can_post.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
