# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # Schema for successful response from reactions.list method
  class ReactionsListSchema < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[Object]]
    attr_accessor :items

    # TODO: Write general description for this method
    # @return [String]
    attr_reader :ok

    # TODO: Write general description for this method
    # @return [PagingObject]
    attr_accessor :paging

    # TODO: Write general description for this method
    # @return [Object]
    attr_accessor :response_metadata

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['items'] = 'items'
      @_hash['ok'] = 'ok'
      @_hash['paging'] = 'paging'
      @_hash['response_metadata'] = 'response_metadata'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        paging
        response_metadata
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(items:, paging: SKIP, response_metadata: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @items = items
      @ok = 'True'
      @paging = paging unless paging == SKIP
      @response_metadata = response_metadata unless response_metadata == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      items = hash.key?('items') ? hash['items'] : nil
      paging = PagingObject.from_hash(hash['paging']) if hash['paging']
      response_metadata =
        hash.key?('response_metadata') ? hash['response_metadata'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ReactionsListSchema.new(items: items,
                              paging: paging,
                              response_metadata: response_metadata,
                              additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} items: #{@items}, ok: #{@ok}, paging: #{@paging}, response_metadata:"\
      " #{@response_metadata}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} items: #{@items.inspect}, ok: #{@ok.inspect}, paging: #{@paging.inspect},"\
      " response_metadata: #{@response_metadata.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
