# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # RemindersCompleteErrorEnum.
  class RemindersCompleteErrorEnum
    REMINDERS_COMPLETE_ERROR_ENUM = [
      # TODO: Write general description for NOT_FOUND
      NOT_FOUND = 'not_found'.freeze,

      # TODO: Write general description for CANNOT_COMPLETE_RECURRING
      CANNOT_COMPLETE_RECURRING = 'cannot_complete_recurring'.freeze,

      # TODO: Write general description for CANNOT_COMPLETE_OTHERS
      CANNOT_COMPLETE_OTHERS = 'cannot_complete_others'.freeze,

      # TODO: Write general description for NOT_AUTHED
      NOT_AUTHED = 'not_authed'.freeze,

      # TODO: Write general description for INVALID_AUTH
      INVALID_AUTH = 'invalid_auth'.freeze,

      # TODO: Write general description for ACCOUNT_INACTIVE
      ACCOUNT_INACTIVE = 'account_inactive'.freeze,

      # TODO: Write general description for TOKEN_REVOKED
      TOKEN_REVOKED = 'token_revoked'.freeze,

      # TODO: Write general description for NO_PERMISSION
      NO_PERMISSION = 'no_permission'.freeze,

      # TODO: Write general description for ORG_LOGIN_REQUIRED
      ORG_LOGIN_REQUIRED = 'org_login_required'.freeze,

      # TODO: Write general description for USER_IS_BOT
      USER_IS_BOT = 'user_is_bot'.freeze,

      # TODO: Write general description for INVALID_ARG_NAME
      INVALID_ARG_NAME = 'invalid_arg_name'.freeze,

      # TODO: Write general description for INVALID_ARRAY_ARG
      INVALID_ARRAY_ARG = 'invalid_array_arg'.freeze,

      # TODO: Write general description for INVALID_CHARSET
      INVALID_CHARSET = 'invalid_charset'.freeze,

      # TODO: Write general description for INVALID_FORM_DATA
      INVALID_FORM_DATA = 'invalid_form_data'.freeze,

      # TODO: Write general description for INVALID_POST_TYPE
      INVALID_POST_TYPE = 'invalid_post_type'.freeze,

      # TODO: Write general description for MISSING_POST_TYPE
      MISSING_POST_TYPE = 'missing_post_type'.freeze,

      # TODO: Write general description for TEAM_ADDED_TO_ORG
      TEAM_ADDED_TO_ORG = 'team_added_to_org'.freeze,

      # TODO: Write general description for INVALID_JSON
      INVALID_JSON = 'invalid_json'.freeze,

      # TODO: Write general description for JSON_NOT_OBJECT
      JSON_NOT_OBJECT = 'json_not_object'.freeze,

      # TODO: Write general description for REQUEST_TIMEOUT
      REQUEST_TIMEOUT = 'request_timeout'.freeze,

      # TODO: Write general description for UPGRADE_REQUIRED
      UPGRADE_REQUIRED = 'upgrade_required'.freeze,

      # TODO: Write general description for FATAL_ERROR
      FATAL_ERROR = 'fatal_error'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      REMINDERS_COMPLETE_ERROR_ENUM.include?(value)
    end

    def self.from_value(value, default_value = NOT_FOUND)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'not_found' then NOT_FOUND
      when 'cannot_complete_recurring' then CANNOT_COMPLETE_RECURRING
      when 'cannot_complete_others' then CANNOT_COMPLETE_OTHERS
      when 'not_authed' then NOT_AUTHED
      when 'invalid_auth' then INVALID_AUTH
      when 'account_inactive' then ACCOUNT_INACTIVE
      when 'token_revoked' then TOKEN_REVOKED
      when 'no_permission' then NO_PERMISSION
      when 'org_login_required' then ORG_LOGIN_REQUIRED
      when 'user_is_bot' then USER_IS_BOT
      when 'invalid_arg_name' then INVALID_ARG_NAME
      when 'invalid_array_arg' then INVALID_ARRAY_ARG
      when 'invalid_charset' then INVALID_CHARSET
      when 'invalid_form_data' then INVALID_FORM_DATA
      when 'invalid_post_type' then INVALID_POST_TYPE
      when 'missing_post_type' then MISSING_POST_TYPE
      when 'team_added_to_org' then TEAM_ADDED_TO_ORG
      when 'invalid_json' then INVALID_JSON
      when 'json_not_object' then JSON_NOT_OBJECT
      when 'request_timeout' then REQUEST_TIMEOUT
      when 'upgrade_required' then UPGRADE_REQUIRED
      when 'fatal_error' then FATAL_ERROR
      else
        default_value
      end
    end
  end
end
