# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # Schema for successful response from rtm.connect method
  class RtmConnectSchema < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_reader :ok

    # TODO: Write general description for this method
    # @return [Self]
    attr_accessor :mself

    # TODO: Write general description for this method
    # @return [Team1]
    attr_accessor :team

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['ok'] = 'ok'
      @_hash['mself'] = 'self'
      @_hash['team'] = 'team'
      @_hash['url'] = 'url'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(mself:, team:, url:, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @ok = 'True'
      @mself = mself
      @team = team
      @url = url
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      mself = Self.from_hash(hash['self']) if hash['self']
      team = Team1.from_hash(hash['team']) if hash['team']
      url = hash.key?('url') ? hash['url'] : nil

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      RtmConnectSchema.new(mself: mself,
                           team: team,
                           url: url,
                           additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} ok: #{@ok}, mself: #{@mself}, team: #{@team}, url: #{@url},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} ok: #{@ok.inspect}, mself: #{@mself.inspect}, team: #{@team.inspect}, url:"\
      " #{@url.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
