# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # ScheduledMessage Model.
  class ScheduledMessage < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :channel_id

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :date_created

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :id

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :post_at

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :text

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['channel_id'] = 'channel_id'
      @_hash['date_created'] = 'date_created'
      @_hash['id'] = 'id'
      @_hash['post_at'] = 'post_at'
      @_hash['text'] = 'text'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        text
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(channel_id:, date_created:, id:, post_at:, text: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @channel_id = channel_id
      @date_created = date_created
      @id = id
      @post_at = post_at
      @text = text unless text == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      channel_id = hash.key?('channel_id') ? hash['channel_id'] : nil
      date_created = hash.key?('date_created') ? hash['date_created'] : nil
      id = hash.key?('id') ? hash['id'] : nil
      post_at = hash.key?('post_at') ? hash['post_at'] : nil
      text = hash.key?('text') ? hash['text'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ScheduledMessage.new(channel_id: channel_id,
                           date_created: date_created,
                           id: id,
                           post_at: post_at,
                           text: text,
                           additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} channel_id: #{@channel_id}, date_created: #{@date_created}, id: #{@id},"\
      " post_at: #{@post_at}, text: #{@text}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} channel_id: #{@channel_id.inspect}, date_created: #{@date_created.inspect},"\
      " id: #{@id.inspect}, post_at: #{@post_at.inspect}, text: #{@text.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
