# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # TeamObject Model.
  class TeamObject < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :archived

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :avatar_base_url

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :created

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :date_create

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :deleted

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :description

    # TODO: Write general description for this method
    # @return [Object]
    attr_accessor :discoverable

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :domain

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :email_domain

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :enterprise_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :enterprise_name

    # TODO: Write general description for this method
    # @return [ExternalOrgMigrations]
    attr_accessor :external_org_migrations

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :has_compliance_export

    # TODO: Write general description for this method
    # @return [ObjsIcon]
    attr_accessor :icon

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :id

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :is_assigned

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :is_enterprise

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :is_over_storage_limit

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :limit_ts

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :locale

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :messages_count

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :msg_edit_window_mins

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :name

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :over_integrations_limit

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :over_storage_limit

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :pay_prod_cur

    # TODO: Write general description for this method
    # @return [Plan]
    attr_accessor :plan

    # TODO: Write general description for this method
    # @return [ObjsPrimaryOwner]
    attr_accessor :primary_owner

    # TODO: Write general description for this method
    # @return [SsoProvider]
    attr_accessor :sso_provider

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['archived'] = 'archived'
      @_hash['avatar_base_url'] = 'avatar_base_url'
      @_hash['created'] = 'created'
      @_hash['date_create'] = 'date_create'
      @_hash['deleted'] = 'deleted'
      @_hash['description'] = 'description'
      @_hash['discoverable'] = 'discoverable'
      @_hash['domain'] = 'domain'
      @_hash['email_domain'] = 'email_domain'
      @_hash['enterprise_id'] = 'enterprise_id'
      @_hash['enterprise_name'] = 'enterprise_name'
      @_hash['external_org_migrations'] = 'external_org_migrations'
      @_hash['has_compliance_export'] = 'has_compliance_export'
      @_hash['icon'] = 'icon'
      @_hash['id'] = 'id'
      @_hash['is_assigned'] = 'is_assigned'
      @_hash['is_enterprise'] = 'is_enterprise'
      @_hash['is_over_storage_limit'] = 'is_over_storage_limit'
      @_hash['limit_ts'] = 'limit_ts'
      @_hash['locale'] = 'locale'
      @_hash['messages_count'] = 'messages_count'
      @_hash['msg_edit_window_mins'] = 'msg_edit_window_mins'
      @_hash['name'] = 'name'
      @_hash['over_integrations_limit'] = 'over_integrations_limit'
      @_hash['over_storage_limit'] = 'over_storage_limit'
      @_hash['pay_prod_cur'] = 'pay_prod_cur'
      @_hash['plan'] = 'plan'
      @_hash['primary_owner'] = 'primary_owner'
      @_hash['sso_provider'] = 'sso_provider'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        archived
        avatar_base_url
        created
        date_create
        deleted
        description
        discoverable
        enterprise_id
        enterprise_name
        external_org_migrations
        has_compliance_export
        is_assigned
        is_enterprise
        is_over_storage_limit
        limit_ts
        locale
        messages_count
        msg_edit_window_mins
        over_integrations_limit
        over_storage_limit
        pay_prod_cur
        plan
        primary_owner
        sso_provider
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        description
      ]
    end

    def initialize(domain:, email_domain:, icon:, id:, name:, archived: SKIP,
                   avatar_base_url: SKIP, created: SKIP, date_create: SKIP,
                   deleted: SKIP, description: SKIP, discoverable: SKIP,
                   enterprise_id: SKIP, enterprise_name: SKIP,
                   external_org_migrations: SKIP, has_compliance_export: SKIP,
                   is_assigned: SKIP, is_enterprise: SKIP,
                   is_over_storage_limit: SKIP, limit_ts: SKIP, locale: SKIP,
                   messages_count: SKIP, msg_edit_window_mins: SKIP,
                   over_integrations_limit: SKIP, over_storage_limit: SKIP,
                   pay_prod_cur: SKIP, plan: SKIP, primary_owner: SKIP,
                   sso_provider: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @archived = archived unless archived == SKIP
      @avatar_base_url = avatar_base_url unless avatar_base_url == SKIP
      @created = created unless created == SKIP
      @date_create = date_create unless date_create == SKIP
      @deleted = deleted unless deleted == SKIP
      @description = description unless description == SKIP
      @discoverable = discoverable unless discoverable == SKIP
      @domain = domain
      @email_domain = email_domain
      @enterprise_id = enterprise_id unless enterprise_id == SKIP
      @enterprise_name = enterprise_name unless enterprise_name == SKIP
      @external_org_migrations = external_org_migrations unless external_org_migrations == SKIP
      @has_compliance_export = has_compliance_export unless has_compliance_export == SKIP
      @icon = icon
      @id = id
      @is_assigned = is_assigned unless is_assigned == SKIP
      @is_enterprise = is_enterprise unless is_enterprise == SKIP
      @is_over_storage_limit = is_over_storage_limit unless is_over_storage_limit == SKIP
      @limit_ts = limit_ts unless limit_ts == SKIP
      @locale = locale unless locale == SKIP
      @messages_count = messages_count unless messages_count == SKIP
      @msg_edit_window_mins = msg_edit_window_mins unless msg_edit_window_mins == SKIP
      @name = name
      @over_integrations_limit = over_integrations_limit unless over_integrations_limit == SKIP
      @over_storage_limit = over_storage_limit unless over_storage_limit == SKIP
      @pay_prod_cur = pay_prod_cur unless pay_prod_cur == SKIP
      @plan = plan unless plan == SKIP
      @primary_owner = primary_owner unless primary_owner == SKIP
      @sso_provider = sso_provider unless sso_provider == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      domain = hash.key?('domain') ? hash['domain'] : nil
      email_domain = hash.key?('email_domain') ? hash['email_domain'] : nil
      icon = ObjsIcon.from_hash(hash['icon']) if hash['icon']
      id = hash.key?('id') ? hash['id'] : nil
      name = hash.key?('name') ? hash['name'] : nil
      archived = hash.key?('archived') ? hash['archived'] : SKIP
      avatar_base_url =
        hash.key?('avatar_base_url') ? hash['avatar_base_url'] : SKIP
      created = hash.key?('created') ? hash['created'] : SKIP
      date_create = hash.key?('date_create') ? hash['date_create'] : SKIP
      deleted = hash.key?('deleted') ? hash['deleted'] : SKIP
      description = hash.key?('description') ? hash['description'] : SKIP
      discoverable = hash.key?('discoverable') ? hash['discoverable'] : SKIP
      enterprise_id = hash.key?('enterprise_id') ? hash['enterprise_id'] : SKIP
      enterprise_name =
        hash.key?('enterprise_name') ? hash['enterprise_name'] : SKIP
      external_org_migrations = ExternalOrgMigrations.from_hash(hash['external_org_migrations']) if
        hash['external_org_migrations']
      has_compliance_export =
        hash.key?('has_compliance_export') ? hash['has_compliance_export'] : SKIP
      is_assigned = hash.key?('is_assigned') ? hash['is_assigned'] : SKIP
      is_enterprise = hash.key?('is_enterprise') ? hash['is_enterprise'] : SKIP
      is_over_storage_limit =
        hash.key?('is_over_storage_limit') ? hash['is_over_storage_limit'] : SKIP
      limit_ts = hash.key?('limit_ts') ? hash['limit_ts'] : SKIP
      locale = hash.key?('locale') ? hash['locale'] : SKIP
      messages_count =
        hash.key?('messages_count') ? hash['messages_count'] : SKIP
      msg_edit_window_mins =
        hash.key?('msg_edit_window_mins') ? hash['msg_edit_window_mins'] : SKIP
      over_integrations_limit =
        hash.key?('over_integrations_limit') ? hash['over_integrations_limit'] : SKIP
      over_storage_limit =
        hash.key?('over_storage_limit') ? hash['over_storage_limit'] : SKIP
      pay_prod_cur = hash.key?('pay_prod_cur') ? hash['pay_prod_cur'] : SKIP
      plan = hash.key?('plan') ? hash['plan'] : SKIP
      primary_owner = ObjsPrimaryOwner.from_hash(hash['primary_owner']) if hash['primary_owner']
      sso_provider = SsoProvider.from_hash(hash['sso_provider']) if hash['sso_provider']

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      TeamObject.new(domain: domain,
                     email_domain: email_domain,
                     icon: icon,
                     id: id,
                     name: name,
                     archived: archived,
                     avatar_base_url: avatar_base_url,
                     created: created,
                     date_create: date_create,
                     deleted: deleted,
                     description: description,
                     discoverable: discoverable,
                     enterprise_id: enterprise_id,
                     enterprise_name: enterprise_name,
                     external_org_migrations: external_org_migrations,
                     has_compliance_export: has_compliance_export,
                     is_assigned: is_assigned,
                     is_enterprise: is_enterprise,
                     is_over_storage_limit: is_over_storage_limit,
                     limit_ts: limit_ts,
                     locale: locale,
                     messages_count: messages_count,
                     msg_edit_window_mins: msg_edit_window_mins,
                     over_integrations_limit: over_integrations_limit,
                     over_storage_limit: over_storage_limit,
                     pay_prod_cur: pay_prod_cur,
                     plan: plan,
                     primary_owner: primary_owner,
                     sso_provider: sso_provider,
                     additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} archived: #{@archived}, avatar_base_url: #{@avatar_base_url}, created:"\
      " #{@created}, date_create: #{@date_create}, deleted: #{@deleted}, description:"\
      " #{@description}, discoverable: #{@discoverable}, domain: #{@domain}, email_domain:"\
      " #{@email_domain}, enterprise_id: #{@enterprise_id}, enterprise_name: #{@enterprise_name},"\
      " external_org_migrations: #{@external_org_migrations}, has_compliance_export:"\
      " #{@has_compliance_export}, icon: #{@icon}, id: #{@id}, is_assigned: #{@is_assigned},"\
      " is_enterprise: #{@is_enterprise}, is_over_storage_limit: #{@is_over_storage_limit},"\
      " limit_ts: #{@limit_ts}, locale: #{@locale}, messages_count: #{@messages_count},"\
      " msg_edit_window_mins: #{@msg_edit_window_mins}, name: #{@name}, over_integrations_limit:"\
      " #{@over_integrations_limit}, over_storage_limit: #{@over_storage_limit}, pay_prod_cur:"\
      " #{@pay_prod_cur}, plan: #{@plan}, primary_owner: #{@primary_owner}, sso_provider:"\
      " #{@sso_provider}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} archived: #{@archived.inspect}, avatar_base_url:"\
      " #{@avatar_base_url.inspect}, created: #{@created.inspect}, date_create:"\
      " #{@date_create.inspect}, deleted: #{@deleted.inspect}, description:"\
      " #{@description.inspect}, discoverable: #{@discoverable.inspect}, domain:"\
      " #{@domain.inspect}, email_domain: #{@email_domain.inspect}, enterprise_id:"\
      " #{@enterprise_id.inspect}, enterprise_name: #{@enterprise_name.inspect},"\
      " external_org_migrations: #{@external_org_migrations.inspect}, has_compliance_export:"\
      " #{@has_compliance_export.inspect}, icon: #{@icon.inspect}, id: #{@id.inspect},"\
      " is_assigned: #{@is_assigned.inspect}, is_enterprise: #{@is_enterprise.inspect},"\
      " is_over_storage_limit: #{@is_over_storage_limit.inspect}, limit_ts: #{@limit_ts.inspect},"\
      " locale: #{@locale.inspect}, messages_count: #{@messages_count.inspect},"\
      " msg_edit_window_mins: #{@msg_edit_window_mins.inspect}, name: #{@name.inspect},"\
      " over_integrations_limit: #{@over_integrations_limit.inspect}, over_storage_limit:"\
      " #{@over_storage_limit.inspect}, pay_prod_cur: #{@pay_prod_cur.inspect}, plan:"\
      " #{@plan.inspect}, primary_owner: #{@primary_owner.inspect}, sso_provider:"\
      " #{@sso_provider.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
