# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # Type.
  class Type
    TYPE = [
      # TODO: Write general description for TEXT
      TEXT = 'text'.freeze,

      # TODO: Write general description for DATE
      DATE = 'date'.freeze,

      # TODO: Write general description for LINK
      LINK = 'link'.freeze,

      # TODO: Write general description for MAILTO
      MAILTO = 'mailto'.freeze,

      # TODO: Write general description for OPTIONS_LIST
      OPTIONS_LIST = 'options_list'.freeze,

      # TODO: Write general description for USER
      USER = 'user'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE.include?(value)
    end

    def self.from_value(value, default_value = TEXT)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'text' then TEXT
      when 'date' then DATE
      when 'link' then LINK
      when 'mailto' then MAILTO
      when 'options_list' then OPTIONS_LIST
      when 'user' then USER
      else
        default_value
      end
    end
  end
end
