# slack_web_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module SlackWebApi
  # UsersSetActiveErrorEnum.
  class UsersSetActiveErrorEnum
    USERS_SET_ACTIVE_ERROR_ENUM = [
      # TODO: Write general description for NOT_AUTHED
      NOT_AUTHED = 'not_authed'.freeze,

      # TODO: Write general description for INVALID_AUTH
      INVALID_AUTH = 'invalid_auth'.freeze,

      # TODO: Write general description for ACCOUNT_INACTIVE
      ACCOUNT_INACTIVE = 'account_inactive'.freeze,

      # TODO: Write general description for TOKEN_REVOKED
      TOKEN_REVOKED = 'token_revoked'.freeze,

      # TODO: Write general description for NO_PERMISSION
      NO_PERMISSION = 'no_permission'.freeze,

      # TODO: Write general description for ORG_LOGIN_REQUIRED
      ORG_LOGIN_REQUIRED = 'org_login_required'.freeze,

      # TODO: Write general description for EKM_ACCESS_DENIED
      EKM_ACCESS_DENIED = 'ekm_access_denied'.freeze,

      # TODO: Write general description for MISSING_SCOPE
      MISSING_SCOPE = 'missing_scope'.freeze,

      # TODO: Write general description for INVALID_ARGUMENTS
      INVALID_ARGUMENTS = 'invalid_arguments'.freeze,

      # TODO: Write general description for INVALID_ARG_NAME
      INVALID_ARG_NAME = 'invalid_arg_name'.freeze,

      # TODO: Write general description for INVALID_CHARSET
      INVALID_CHARSET = 'invalid_charset'.freeze,

      # TODO: Write general description for INVALID_FORM_DATA
      INVALID_FORM_DATA = 'invalid_form_data'.freeze,

      # TODO: Write general description for INVALID_POST_TYPE
      INVALID_POST_TYPE = 'invalid_post_type'.freeze,

      # TODO: Write general description for MISSING_POST_TYPE
      MISSING_POST_TYPE = 'missing_post_type'.freeze,

      # TODO: Write general description for TEAM_ADDED_TO_ORG
      TEAM_ADDED_TO_ORG = 'team_added_to_org'.freeze,

      # TODO: Write general description for REQUEST_TIMEOUT
      REQUEST_TIMEOUT = 'request_timeout'.freeze,

      # TODO: Write general description for FATAL_ERROR
      FATAL_ERROR = 'fatal_error'.freeze,

      # TODO: Write general description for INTERNAL_ERROR
      INTERNAL_ERROR = 'internal_error'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      USERS_SET_ACTIVE_ERROR_ENUM.include?(value)
    end

    def self.from_value(value, default_value = NOT_AUTHED)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'not_authed' then NOT_AUTHED
      when 'invalid_auth' then INVALID_AUTH
      when 'account_inactive' then ACCOUNT_INACTIVE
      when 'token_revoked' then TOKEN_REVOKED
      when 'no_permission' then NO_PERMISSION
      when 'org_login_required' then ORG_LOGIN_REQUIRED
      when 'ekm_access_denied' then EKM_ACCESS_DENIED
      when 'missing_scope' then MISSING_SCOPE
      when 'invalid_arguments' then INVALID_ARGUMENTS
      when 'invalid_arg_name' then INVALID_ARG_NAME
      when 'invalid_charset' then INVALID_CHARSET
      when 'invalid_form_data' then INVALID_FORM_DATA
      when 'invalid_post_type' then INVALID_POST_TYPE
      when 'missing_post_type' then MISSING_POST_TYPE
      when 'team_added_to_org' then TEAM_ADDED_TO_ORG
      when 'request_timeout' then REQUEST_TIMEOUT
      when 'fatal_error' then FATAL_ERROR
      when 'internal_error' then INTERNAL_ERROR
      else
        default_value
      end
    end
  end
end
